<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Instruction Type</name>
   <tag></tag>
   <elementGuidId>2903a823-9cf2-4d17-8846-abf732806612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#earningType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'earningType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Benefit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>8cdd9027-2db0-4f1b-9f00-b4d1b33999b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>2f38c27b-97fd-43b2-b87d-b4cb662acbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>135fdb55-592d-4232-b6e4-ba6b3a5182bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>EarningTypeObjId</value>
      <webElementGuid>1ce3c3d9-d21f-4b37-aba4-a27842d42088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>6c1c1435-0a8e-4a39-a427-ecca33c17b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>earningType</value>
      <webElementGuid>8266a03a-3588-427c-be9c-9211758cc124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>dffa685b-d284-42ed-ab75-ab79d1ae1525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8bf05fc4-0234-46b9-bd4f-11b051080ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Benefit</value>
      <webElementGuid>4f76672d-5bb7-4690-8ee9-ddb464a69dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instruction Type</value>
      <webElementGuid>1f81d740-210d-43b2-a28b-a0f52b14dc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Benefit</value>
      <webElementGuid>a65440d9-49f6-4d86-bf09-01b786bb40e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c1cc50b302543504a3e1a359e45e25cb</value>
      <webElementGuid>224bba8b-fc2f-4a28-91aa-5bd792688e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'earningType']</value>
      <webElementGuid>800af409-2b31-42ca-a0a2-dd73c7b262a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'earningType']</value>
      <webElementGuid>8c774963-f64a-4647-b0b1-6200d10d5e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'earningType' and @title = 'Benefit' and (text() = 'Instruction Type' or . = 'Instruction Type')]</value>
      <webElementGuid>b94fbeab-f214-4261-8a35-117cdf66b09d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
