<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Input value type</name>
   <tag></tag>
   <elementGuidId>f5459dec-651e-46f8-a51a-f8ae200a4c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputTypeObjId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'inputTypeObjId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Hours&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>b4611ab0-e744-48c1-ae68-b4db360f71ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputTypeObjId</value>
      <webElementGuid>664fe9e7-1f67-4346-9ad9-0e0a136a85c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>c4d9f040-2574-4e8e-b326-7cd97c21f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>09b968d8-6cad-429a-8930-182f01e133ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>InputTypeObjId</value>
      <webElementGuid>0f4e1e3a-3c47-4302-84d2-2a30e7be0536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>f2f3f3d5-9dda-46ac-9e4a-ece3e0ce5bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b78141c3-a75a-421f-b8bc-be9be6614122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec0fea25-ba75-4267-a863-deaedefd0efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>c27a6855-fc4c-4e5c-917b-565a931ff0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Input value type</value>
      <webElementGuid>bd5ff1ad-e4c8-4ff9-b055-6b1ef88a4894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>e4b443d5-c1eb-4ebd-9261-8022042d0ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fec515dfd93c0de8f5fcf167069b9c87</value>
      <webElementGuid>a296ce92-87a7-4600-a5c9-44072095138a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>077143cf-691f-481c-a08a-262a3b0980b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>bced21e4-8bd3-49ab-9f4a-eafe7d163845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'inputTypeObjId' and @title = 'Hours' and (text() = 'Input value type' or . = 'Input value type')]</value>
      <webElementGuid>c27f82c4-44b8-4677-b03e-88d478142742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
