<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Default Value</name>
   <tag></tag>
   <elementGuidId>a1549854-1ebd-4010-ba26-fdf7be8cdfce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#defaultValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'defaultValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Default Value:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c6de136-a258-46ae-96ab-25486c9f7a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>52f3a8c7-f07b-4646-872a-86bf2f19d827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defaultValue</value>
      <webElementGuid>64794d78-d4e3-4e54-98f6-5fe20157e181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DefaultValue</value>
      <webElementGuid>aa6c805e-b7da-4cd5-b518-45aff3463f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--small ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cb712a36-3d60-4d85-ac12-ed6a484d0ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default Value</value>
      <webElementGuid>6e55d305-2632-4237-b6a9-6f465cde631b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fc3eeb1fc46f11015e5684fba8be5b9a</value>
      <webElementGuid>0ed96b62-061c-4ac3-b2bc-e5d19971c85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'defaultValue']</value>
      <webElementGuid>6cb8e782-a18e-4da8-8173-3af71d2208bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'defaultValue']</value>
      <webElementGuid>67e95405-ca53-4272-a4ad-ec0993c97d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'defaultValue' and (text() = 'Default Value' or . = 'Default Value')]</value>
      <webElementGuid>2f5ee79c-b92d-4a6d-8ab0-095e56fccf68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
