<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applies to</name>
   <tag></tag>
   <elementGuidId>7fef306f-3f6c-47f0-b44f-c877cbd6433a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isAppliedToAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'isAppliedToAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Applies to:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7cfebb4-7cc3-4a4d-9cb7-ecf510f20246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>39e4323f-3db5-42b2-92aa-e61281d86ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isAppliedToAll</value>
      <webElementGuid>20700c1c-4cc9-403c-a390-c3add1d09e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>IsAppliedToAll</value>
      <webElementGuid>7acc4732-67bf-46ac-83c0-cb253b1886be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-checkbox ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>486834fd-f788-4a7f-935d-c1a21d51b5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Applies to</value>
      <webElementGuid>25c69880-641b-4603-8f21-5f710b0178aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e2adbcc22a1f1dadda78e6acc2984fe</value>
      <webElementGuid>3f96ae78-1a74-4224-b4be-cf01ef4dc96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'isAppliedToAll']</value>
      <webElementGuid>0adb104c-39ae-4142-8d22-a5ac41544da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'isAppliedToAll']</value>
      <webElementGuid>34aba1f0-d1bd-40ad-a345-ce54030b19c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isAppliedToAll' and (text() = 'Applies to' or . = 'Applies to')]</value>
      <webElementGuid>2d0d8cf4-d6af-4913-b519-39b67369d3b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
