<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nameFrench</name>
   <tag></tag>
   <elementGuidId>d9761aa6-e1df-4a0f-9d1d-2013353d65f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameFrench</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nameFrench']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nameFrench</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8b4dea7-b7a7-47f5-8877-854f3d0a42a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e55ca94-86b1-48fa-befe-b60774a7f769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>24dbd97c-d9d6-48b3-8207-34bbe5c69c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>NameFrench</value>
      <webElementGuid>a991c8a7-f42b-4051-8fbd-efb297236993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>35fb9704-e7b8-4e7a-931d-c1f5cc42c732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>1babdd52-0eb4-4d98-97ce-b8649949ea57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b2d50dbd89a59c761b01381853be16aa</value>
      <webElementGuid>7a163af1-50b4-4814-88cf-022ecf7fb074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>cf7bf332-99ad-43ac-b63d-99736013d232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>4cc959cf-0592-4b65-9a8a-3cae29343b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameFrench' and (text() = 'nameFrench' or . = 'nameFrench')]</value>
      <webElementGuid>f876447a-28a2-43fa-aeb9-6fe700869c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
