<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description</name>
   <tag></tag>
   <elementGuidId>cfa655d9-afae-4de3-b51c-8ecf5a90fb96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descriptionEnglish</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'descriptionEnglish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6af14922-1708-4929-b8db-7d9af63edc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>407aa597-ec71-4e46-bf9b-76bdfdf6e100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionEnglish</value>
      <webElementGuid>8ad15bf1-c573-4a9f-aa6b-17943b44e32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DescriptionEnglish</value>
      <webElementGuid>468f6ec3-25b8-4245-9697-4cec1779c82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2f11e443-1698-48a2-a0fc-92b7ea87a680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>5bcb2086-b0d0-4c15-b082-6203d19eb2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e53d8606c1bcb0a98aafdcb52c7855b9</value>
      <webElementGuid>40fd47ae-554a-47e6-863a-921fe36ddbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionEnglish']</value>
      <webElementGuid>a50b85c3-f5bb-4485-adda-67538b4ad72a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionEnglish']</value>
      <webElementGuid>ce87c7e0-fc2b-4aed-81ec-245425b50d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionEnglish' and (text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>1f0ef237-0085-49b6-a37f-7fffac1235ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
