<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_descriptionFrench</name>
   <tag></tag>
   <elementGuidId>284322e6-68b7-447f-937c-22fd21a890fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descriptionFrench</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'descriptionFrench']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#descriptionFrench</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>422b9e63-ebca-4240-8c52-1f2990e776b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ffd8483-0c07-4104-a158-eff38ede54ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionFrench</value>
      <webElementGuid>7ebf4146-4e41-49ab-baa2-0c8fe830371b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DescriptionFrench</value>
      <webElementGuid>794e4909-50ce-4e21-9edd-94ac7e94d5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>88dd1956-31ba-4ef4-b97a-845d96435d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>descriptionFrench</value>
      <webElementGuid>e91f85e9-f494-4dd2-9db7-1d61559423a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-649358ba2d05fbd009bd6d6be69ad53d</value>
      <webElementGuid>1a5b11e9-93fb-44cb-9964-88eaa2c0514f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionFrench']</value>
      <webElementGuid>398adf72-5622-4a90-9547-e916a760e7ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionFrench']</value>
      <webElementGuid>bc183588-53bb-40e3-aae1-a3817e1a6983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionFrench' and (text() = 'descriptionFrench' or . = 'descriptionFrench')]</value>
      <webElementGuid>798aacaf-753a-44f7-a9b9-6654dece8ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
