<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_defaultFormula</name>
   <tag></tag>
   <elementGuidId>d1fe8b9e-f248-414b-aa26-a1f7a9e44ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#defaultFormula</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'defaultFormula']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#defaultFormula</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5de1cc13-ac6d-4211-987d-753e7633b1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>bef2a3e0-0cca-48b8-8e63-92d9259da734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>d0c81d40-1427-4f83-aec5-e4dd33efa589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9f50eeb8-b1f8-4ab5-ab22-880595d646fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>6f1f3e77-30ba-4d2a-8709-d2e5311311db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c1bf5925-c743-4d37-a851-6f9e758dd55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DefaultFormula</value>
      <webElementGuid>a6fbebb3-5f27-45f2-bf4e-5d5f9ef94906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a9e1b097-6d51-46c7-b0dc-9b11bdefcd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>c8a87c23-c8bd-4d11-9d93-2360e4f4bbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>0799e9cd-3874-49a6-8a5b-049eb4f0a095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-287cb90c8af5d1c88243b2405e542df6</value>
      <webElementGuid>d91c1bcf-0d25-4f5b-959b-ead8f1d72cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'defaultFormula']</value>
      <webElementGuid>dd5968f1-7419-492b-a393-9a926b2e3b6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'defaultFormula']</value>
      <webElementGuid>ed43fbdc-3dd8-43f6-8903-a012cef3f9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'defaultFormula' and @id = 'defaultFormula' and (text() = 'defaultFormula' or . = 'defaultFormula')]</value>
      <webElementGuid>35e15539-efdb-4d17-b2d2-a31256dfbe4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
