<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Schedule</name>
   <tag></tag>
   <elementGuidId>c55d0730-894f-4939-9adc-a1c8097d39fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frequency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'frequency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#frequency</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>caecba94-c68d-45bc-a387-31bc2129682b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>b5ec0b76-32c6-4fe6-a94d-c57b876dd07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>9395295f-6eeb-48ee-b9ae-2ddb1fb0d2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DefaultFrequencyObjId</value>
      <webElementGuid>2df16c18-8c7f-40a0-9583-71e354d9bcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>7fe60e14-887b-41ab-80ee-4d5ec44477cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frequency</value>
      <webElementGuid>a3915709-3adc-4166-8738-45b128a0f8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b18b37c1-c934-4236-9f49-894a1b7ac69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9122ed6f-120f-4223-bf26-b0d6c1157771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select Schedule --</value>
      <webElementGuid>c74ce628-8bff-4fab-94ae-c4c1e60a3a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Schedule</value>
      <webElementGuid>cde4507f-3752-458a-bd8b-ac6415c7667f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>--Select Schedule --</value>
      <webElementGuid>ab6cdb2e-0cbc-4924-b41f-cc8f7ab4b52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-041b19ae70781f0af9df7a5fe525a1ba</value>
      <webElementGuid>cd65c3bc-da05-484f-9af3-897506d0cfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'frequency']</value>
      <webElementGuid>081901f6-c841-44e2-8776-f70329da5604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'frequency']</value>
      <webElementGuid>cf2095a8-5b08-4fc9-9af4-6aacafcd24c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'frequency' and @title = '--Select Schedule --' and (text() = 'Schedule' or . = 'Schedule')]</value>
      <webElementGuid>ea914b17-3356-4568-863a-787c351a6d6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
