<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Input value type</name>
   <tag></tag>
   <elementGuidId>6eac7731-b031-4aa9-acac-c9344666240e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputTypeObjId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'inputTypeObjId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Hours&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>08d14f82-093c-4369-8d4c-615e7e9d1a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputTypeObjId</value>
      <webElementGuid>f668d704-1c11-43a5-b175-7c1a36920c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>8d44b494-28ce-4db2-8f46-7e0241cc1974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>5d0afe7b-bee6-40ac-92a0-aea3f027b5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>InputTypeObjId</value>
      <webElementGuid>3d4b6576-0cdf-42a6-a2fb-991eae5ef8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>f3d997cd-32ac-4171-8bb3-70a6bbcbfd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>fcfa2051-ed3f-47bb-b1d4-3b51bb571cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3eba50ec-2b58-418d-856b-e8032b3c51e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>aeade618-bd5d-4610-9186-9b8211431623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Input value type</value>
      <webElementGuid>a4fbce88-feca-4fb5-be8f-34da293edb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>b4d506ca-b510-49a6-93ac-43f27f09a4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fec515dfd93c0de8f5fcf167069b9c87</value>
      <webElementGuid>8acfba14-3ce0-4117-9715-1b504c3f11ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>0fda1a5b-d5c3-4ba7-8b37-8158e96ebcb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>076b4c01-f5fe-4568-b392-bb1d85fa2a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'inputTypeObjId' and @title = 'Hours' and (text() = 'Input value type' or . = 'Input value type')]</value>
      <webElementGuid>8a77b2f0-6d18-46a5-b6ea-f9bd6813439e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
