<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_descriptionFrench</name>
   <tag></tag>
   <elementGuidId>5b6d2d2d-84b0-4040-8c4a-1a9e49aaa7be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descriptionFrench</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'descriptionFrench']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#descriptionFrench</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e40d2b74-6c77-4182-88a8-9031f16f8b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8d565d3-add7-4075-8075-908f99a28a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionFrench</value>
      <webElementGuid>ae4eb246-98f8-434a-959a-eb1c58a7418a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DescriptionFrench</value>
      <webElementGuid>b34b5683-d4cc-404a-b409-578fc7643281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8c037698-5e23-4f6c-b225-2a698c7ea97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>descriptionFrench</value>
      <webElementGuid>142aed4b-caad-423a-91eb-c3b58d955f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-649358ba2d05fbd009bd6d6be69ad53d</value>
      <webElementGuid>b5f61725-c9e4-4099-83e9-86f1284cf06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionFrench']</value>
      <webElementGuid>6aedfe8e-1d46-42d0-aa8a-cbd2867e4710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionFrench']</value>
      <webElementGuid>44237d17-107e-4ae7-a057-19898ce75685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionFrench' and (text() = 'descriptionFrench' or . = 'descriptionFrench')]</value>
      <webElementGuid>78ad2733-412c-49d3-a4d4-57d855083a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
