<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description</name>
   <tag></tag>
   <elementGuidId>73b2f5d2-e1fc-46f3-807c-0404d1abfcb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descriptionEnglish</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'descriptionEnglish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfca53c4-17d7-4b8d-9cab-2627d48375aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34cbc661-8191-415d-a053-a938e2fecaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionEnglish</value>
      <webElementGuid>fc403926-ee0a-4e41-9cd9-f06ed16c8655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DescriptionEnglish</value>
      <webElementGuid>fb1ae6cc-6474-4fff-b8e1-dc40dceb0c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8f0ee4af-49e5-4fc5-82c6-a53acf2c7437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>83a8b689-436b-48bf-9ff0-64d6ce958414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e53d8606c1bcb0a98aafdcb52c7855b9</value>
      <webElementGuid>007fc449-8d16-4907-a0e3-c2b8808cf197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionEnglish']</value>
      <webElementGuid>059ec204-da2b-48db-9164-321924bd19f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionEnglish']</value>
      <webElementGuid>e42b9329-8715-4142-bef7-4b77fa2b9b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionEnglish' and (text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>b046f6b8-1d62-4efc-97b4-bf8f1663d019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
