<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name</name>
   <tag></tag>
   <elementGuidId>ea9ca751-8044-4bb8-a901-a5c8ae64e8a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameEnglish</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nameEnglish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Name:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>753a737b-d096-41c0-8c84-92e79b00fd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93c0fb49-77c5-4e23-8ab5-392d9f63bcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameEnglish</value>
      <webElementGuid>55c417af-e0c5-459e-8c1c-634fc7cfec9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>NameEnglish</value>
      <webElementGuid>4f2bc515-8c20-4179-8c04-b9cd71c6c1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>72de4bf7-fc1b-4b77-9504-cfb733ed2382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>a5b7eb0d-c591-4353-b5c4-d0fc2c9e1979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ada4c29eec15e5aa44348b6f247307b2</value>
      <webElementGuid>f6e1057f-ccd6-49cb-8e55-570544203864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nameEnglish']</value>
      <webElementGuid>8220dfdf-4578-4259-b865-3436a34f0755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nameEnglish']</value>
      <webElementGuid>9fc53cf6-b30b-4a64-9065-66033e9b0c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameEnglish' and (text() = 'Name' or . = 'Name')]</value>
      <webElementGuid>4ba6fd14-ceab-4013-9f53-9bf91937fee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
