<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anns Test Org</name>
   <tag></tag>
   <elementGuidId>5563cb15-7eb8-4b9f-b39c-0609e2d35bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ann's Test Org&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30fc038f-f59f-4756-9901-b5d1db04d139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CloseDialog(0);</value>
      <webElementGuid>3a81b7cd-b1ef-4b47-9065-640188f80900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6</value>
      <webElementGuid>2cc9a4ef-b10f-4e5e-9dc0-429dd97edd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ann's Test Org</value>
      <webElementGuid>5c1da28c-a0ba-41ef-bc55-7683fc06d1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridOrganizationDialogResults&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[1]</value>
      <webElementGuid>9279a37c-9f48-42d8-b18f-3630b7f175af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      <webElementGuid>0d525078-a010-4ef6-9b6b-e865f660a5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridOrganizationDialogResults']/tbody/tr[4]/td[2]/a</value>
      <webElementGuid>13f43444-d496-46b3-9986-cb9f0745d09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP7'])[1]/following::a[1]</value>
      <webElementGuid>7f34dfcd-6fe5-490d-9806-1ea5bf4087e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ann BC Org'])[1]/following::a[2]</value>
      <webElementGuid>62815626-4459-4812-a163-fe69d3a0c9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP-2'])[1]/preceding::a[1]</value>
      <webElementGuid>b900e76c-ae1e-4807-a4ab-ecd673c7e879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6')])[2]</value>
      <webElementGuid>3a96cb42-ba9a-410d-9825-8f63cb36d1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a</value>
      <webElementGuid>1e2c6eb9-3a8e-42c6-b060-efffd38e0d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6' and (text() = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;) or . = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;))]</value>
      <webElementGuid>4e135bbc-72d6-4658-bb1f-00af8ff94aa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
