<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Client 100</name>
   <tag></tag>
   <elementGuidId>a9b598f8-035c-4da2-968d-55b2a51df161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerOrganizationName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headerOrganizationName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Client 100&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a38f0b1-d586-419a-bd76-4135cc124d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-menu__organization</value>
      <webElementGuid>58a9595a-a400-41e3-945b-3e81971e1a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headerOrganizationName</value>
      <webElementGuid>75181c8c-9933-4096-a41e-e57f36b7ad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Client 100
                                        </value>
      <webElementGuid>ef2fcae5-1206-4671-931d-29a355f3bed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerOrganizationName&quot;)</value>
      <webElementGuid>d4b14e3a-b235-48f6-b02a-16d0bab30d9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headerOrganizationName']</value>
      <webElementGuid>f283d0db-c849-4eba-9f2f-ac6b280cefb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-user-menu']/div/div/div[2]</value>
      <webElementGuid>2f835c50-d0c4-4db5-a575-efba561a8075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Darryl Stewart'])[1]/following::div[1]</value>
      <webElementGuid>1d388b6f-3d6b-4f7f-a3d9-f30e85f81612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::div[7]</value>
      <webElementGuid>074cff68-5881-423b-9d68-c5da2e484817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='expand_more'])[1]/preceding::div[1]</value>
      <webElementGuid>f730e227-21ce-47ad-8ad4-57324d52ef42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Client 100']/parent::*</value>
      <webElementGuid>3d78f80a-dbed-4d7d-bad1-e130f53d2ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>6c3f4f64-9ad1-425d-8338-39d0cdc4f92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headerOrganizationName' and (text() = '
                                            Client 100
                                        ' or . = '
                                            Client 100
                                        ')]</value>
      <webElementGuid>8a6bb96b-d06e-47ff-bace-75318bbd1497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
