<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_expand_more</name>
   <tag></tag>
   <elementGuidId>5d48f6a0-13e6-4eec-9213-8069295ab09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-user-menu']/div/div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.header-menu__icon > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;expand_more&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2f0484e7-9bd8-4922-8269-11ad8d1e4c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>34a74854-4a24-4126-8ebc-a0dde0f17f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>expand_more</value>
      <webElementGuid>f5861b28-5f25-4069-9911-f5e73d26fda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-user-menu&quot;)/div[@class=&quot;header-menu__button&quot;]/div[@class=&quot;header-menu__icon&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>4139f96b-a061-4ada-a9ff-abc8bf8380f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-user-menu']/div/div[2]/i</value>
      <webElementGuid>e3a75073-b882-4fc8-bdcb-4e5911bee490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client 100'])[1]/following::i[1]</value>
      <webElementGuid>9d37a2de-c27a-4873-9dc7-f6751c634459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Darryl Stewart'])[1]/following::i[1]</value>
      <webElementGuid>a64be946-69e4-49be-85b3-0fba935aff96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='swap_horiz'])[1]/preceding::i[1]</value>
      <webElementGuid>7dab55eb-0f08-4ea1-b89f-6f5acc387b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='expand_more']/parent::*</value>
      <webElementGuid>3fc60693-453e-4893-a8f5-3b69fc09326b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/i</value>
      <webElementGuid>08664f23-bded-46a6-b71a-d44eaabdb12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'expand_more' or . = 'expand_more')]</value>
      <webElementGuid>24cf85c6-5453-4327-9eed-4cf6f8761ac9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
