<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Employee Portal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f78874bc-a7b5-4c96-ae9d-6f30fd8e4b1d</testSuiteGuid>
   <testCaseLink>
      <guid>a185b266-9a82-4166-8810-60e73425be6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Employee Portal/TC-EP-01-Login_as_First_emplyoee_and_NavigateToCurrentPayPeriod</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a22d27d-6155-4387-8586-be2f522ab2f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b860f6fe-2fb1-4b49-9cd5-327728ba2cc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b841eea-aa56-4db0-998c-795b22b9950a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90f9bf00-312f-4d28-b472-932d7ff574b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Employee Portal/TC-EP-02 VerifyShiftsAreVisibleFromScheduleData</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c98d33f8-9b09-4484-8a92-bdf879447729</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b230db1a-72a4-4771-a416-b6535c89f577</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>928b99d6-49c9-40d9-9c8b-15caca9fdc70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Employee Portal/TC-EP-03_SwitchBetweenView and verify checkbox in week view</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>65f7543a-7116-4780-bd60-f667cbb58437</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Employee Portal/TC-EP-04_confirm the shift</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2d15778-9554-4522-b47e-c62c1d51120c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13dd0635-0892-469a-a0a1-1e914176da03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf7b87bd-b1c2-4a09-a449-07b5ff76886a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>722cab7b-7440-48b1-811c-cb1fc2b02536</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Employee Portal/TC-EP-05_Navigate_to_TimeEntry-Add_and_confirm_shift_for_tuesday</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>404a29bb-956f-4f5f-a73d-ca427f8dd067</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c3b9e6-00ff-45c7-bb5a-b0f65adf3ef8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdefc0de-d5fe-4ff3-9111-ad6377b89d3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>925ac886-6e02-467f-b811-4444e2b12f76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6356789-3186-4bbb-868a-02809a4447fc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
