<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Everest_regression_test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3d36cb61-98e5-4386-8891-8bd5517360a4</testSuiteGuid>
   <testCaseLink>
      <guid>596be301-037e-403a-82f6-f181f5814bba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Home/TC-Home-01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c89905a-8593-4c1e-b5ac-432b80d052b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62d61f89-50de-4e60-94ac-be135de3e718</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad906376-bec7-4478-8fec-2dd1654d62a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Schedules/TC-SCH-01_OpenSchedulesSlider</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>41b7b805-e5ff-4c41-abe5-f8ae0ee8a503</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Schedules/TC-SCH-02_VerifyScheduleListing</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6401623-cbd0-4545-b712-5c982aeabe89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23d257fc-5c75-43db-ba3a-2cf1d3f8a352</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dc5f5bc-0947-4c7d-b21b-554962af7af8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Schedules/TC-SCH-03_AddAndPostShift</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3476c993-6954-4c9a-a07f-05e8ded4bec0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75386c43-a762-4542-ba9f-cd1653ec76d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcf73175-31cf-47d3-9337-3d82cc9518ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c492c6f-4924-4109-b52e-bd913165efbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f4d8360-ac7e-4661-b883-55e89e9cf12e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cc9e7f9-165d-416e-a4c9-dc1ab5ff193e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f9c3feb-7809-47a9-94e7-e2f96287eebc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d6b55c-495a-4b67-9298-5bb7601649d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ce49ae-0a6e-4b2c-ada7-84df4cad36a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f5d7dd8-016f-4dbf-a1db-99e79d7c1874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f12eb1ce-3781-4b0f-827f-5e5f79108349</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17f2ef2b-12a7-467b-b75d-9bd85f51f5bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Daily Approval/TC-DA-01_OpenDailyApproval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad74bc1e-a557-4e85-a742-e893410b656d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40d7120-1823-4c98-a408-5d9ac3e0bcdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a95eac5-7ddb-4804-9213-a57afe8f0b01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Everest_Regression_Tests/Daily Approval/TC-DA-02_ApproveAndLockShifts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
