<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Biweekly-27</name>
   <tag></tag>
   <elementGuidId>6a4376c2-a079-4fbe-bdc3-79ba7a827afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='CloseDialog(0);'])[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Biweekly-27&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>573f2c8d-10ce-4c35-ab3e-9ed6ed2987b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CloseDialog(0);</value>
      <webElementGuid>f1d69008-1e95-4d94-99e9-c82ab89c08ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edge5/everest/OrganizationContext/ChangeContext.mr?OrganizationId=5a49cd44-15cd-449e-b4ee-1279e3088dc2</value>
      <webElementGuid>8a7b891d-1f61-49f6-89b9-21a649fb3a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biweekly-27</value>
      <webElementGuid>297e1f9b-2de2-4bfa-a669-9c9e559c3539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridOrganizationDialogResults&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[2]/a[1]</value>
      <webElementGuid>665152d9-a12d-405f-9c25-df5542442c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='CloseDialog(0);'])[18]</value>
      <webElementGuid>6c03665f-cae1-4a31-a006-83e2a14e2324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridOrganizationDialogResults']/tbody/tr[9]/td[2]/a</value>
      <webElementGuid>74097858-acba-46cb-a0e7-29531f0ef293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Biweekly-27')]</value>
      <webElementGuid>595e6641-2412-48f4-adaf-aacb94f007ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biweekly-26'])[1]/following::a[2]</value>
      <webElementGuid>3cc8aa58-244e-40dc-a9e4-a40ed65ac231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BC Test Org'])[2]/following::a[4]</value>
      <webElementGuid>44f42dc0-e820-44fb-8d68-3d97b71765ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B1'])[1]/preceding::a[1]</value>
      <webElementGuid>4d8e76c1-d0cd-45a5-b14b-ca3b4c8f9220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonus Tax Test Org'])[1]/preceding::a[2]</value>
      <webElementGuid>96b689b0-54d2-464a-aeb2-2d8ed3866fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Biweekly-27']/parent::*</value>
      <webElementGuid>12bf0206-3d6d-4d51-8622-f3d0ef8574e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/edge5/everest/OrganizationContext/ChangeContext.mr?OrganizationId=5a49cd44-15cd-449e-b4ee-1279e3088dc2')])[2]</value>
      <webElementGuid>32677aae-ed5d-4a35-ae6b-3dedcb823951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/a</value>
      <webElementGuid>9a6e22c1-9211-4af3-a1c0-0831fdeb56fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edge5/everest/OrganizationContext/ChangeContext.mr?OrganizationId=5a49cd44-15cd-449e-b4ee-1279e3088dc2' and (text() = 'Biweekly-27' or . = 'Biweekly-27')]</value>
      <webElementGuid>3f8850ee-8ab7-49df-9b37-8bb591c027e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
