<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_swap_horiz Switch SetupSimpleDialog(orgCo_626e67</name>
   <tag></tag>
   <elementGuidId>18ea4f2e-8a9e-49c3-a2ee-4451783a1872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contextSwitch--navheader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='contextSwitch--navheader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;swap_horiz Switch&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95c960b1-c75a-4c5a-a655-c303436f015a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contextSwitch--navheader</value>
      <webElementGuid>82a0262c-aa9e-4709-ab0c-9851174cebc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e87d785e-be59-47ec-9b54-7a23b0111294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navheader__icon-link-stack u-m-horizontal</value>
      <webElementGuid>6703b274-6468-4db9-b9b1-11b2deedc74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swap_horiz Switch SetupSimpleDialog('orgContextList', 'Organizations', 'contextSwitch--navheader', '/Edge5/Everest/OrganizationContext/Index.mr', '', 'autoOpen:false,width:800,height:480,modal:true,draggable:false,resizable:false'); </value>
      <webElementGuid>59e51f61-c431-463e-bd94-06e3b1c5a66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contextSwitch--navheader&quot;)</value>
      <webElementGuid>51949f96-29e6-4237-8dab-8363e01bcb1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='contextSwitch--navheader']</value>
      <webElementGuid>3b6ecf38-5697-4ded-8c23-9185049ac5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='exit_to_app'])[1]/following::a[1]</value>
      <webElementGuid>ef900e2d-a63e-4412-8a0c-cd74e1d4555c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Switch']/parent::*</value>
      <webElementGuid>5592b5bb-703f-4ce4-bf5e-d81508b62247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>646a96e8-ef4b-474d-a299-ff80887bf6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>903e5daf-f663-4993-89bb-12239584020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'contextSwitch--navheader' and @href = 'javascript:void(0);' and (text() = concat(&quot;swap_horiz Switch SetupSimpleDialog(&quot; , &quot;'&quot; , &quot;orgContextList&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Organizations&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;contextSwitch--navheader&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;/Edge5/Everest/OrganizationContext/Index.mr&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;autoOpen:false,width:800,height:480,modal:true,draggable:false,resizable:false&quot; , &quot;'&quot; , &quot;); &quot;) or . = concat(&quot;swap_horiz Switch SetupSimpleDialog(&quot; , &quot;'&quot; , &quot;orgContextList&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Organizations&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;contextSwitch--navheader&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;/Edge5/Everest/OrganizationContext/Index.mr&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;autoOpen:false,width:800,height:480,modal:true,draggable:false,resizable:false&quot; , &quot;'&quot; , &quot;); &quot;))]</value>
      <webElementGuid>ea1bd2c4-a9cd-4ad8-99ee-e8cf388046cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
