<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Schedules</name>
   <tag></tag>
   <elementGuidId>b3a8b32d-c1d7-44cd-9c85-97f024ccc2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='schedules-menu-item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedules-menu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Schedules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9bd38194-ec0b-48ab-ba50-f92be8c20251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.ibexpayroll.com:8443/main/everestspa/schedules</value>
      <webElementGuid>b5a30a37-8662-4b42-b6e3-f0d458801bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedules-menu-item</value>
      <webElementGuid>968a3055-ae93-42bc-bada-e8353638d3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Schedules</value>
      <webElementGuid>4e778a85-a58b-49e7-94dc-a504b1bc56b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedules-menu-item&quot;)</value>
      <webElementGuid>f464dd90-944e-41a1-822a-e92e781b97cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='schedules-menu-item']</value>
      <webElementGuid>c2fdf1b0-8560-45a6-b8b7-96a844fa9c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-navigation-list']/li[2]/a</value>
      <webElementGuid>312e3354-97bb-4183-8f0c-3fc702ad3a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Schedules')]</value>
      <webElementGuid>4333dcd9-77b7-4eac-8d5e-2635a15f0c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>0f682cd4-8f40-4ff6-a374-73f40fd8cdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info_outline'])[2]/following::a[2]</value>
      <webElementGuid>86366a51-0799-4d15-a5a8-1e2ed4e87e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Schedule'])[1]/preceding::a[1]</value>
      <webElementGuid>f643c9a6-ec4e-45bf-bbd4-b7dd37dd2671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chevron_right'])[1]/preceding::a[2]</value>
      <webElementGuid>bf166962-df13-4922-bb94-0c670d03c9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Schedules']/parent::*</value>
      <webElementGuid>c0007388-3a16-4436-ae5c-fb3b5fbd0a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.ibexpayroll.com:8443/main/everestspa/schedules')]</value>
      <webElementGuid>2922d862-1a24-4090-a170-b22698849fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>b12635e1-4973-4f74-8b75-eb822d6047d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.ibexpayroll.com:8443/main/everestspa/schedules' and @id = 'schedules-menu-item' and (text() = ' Schedules' or . = ' Schedules')]</value>
      <webElementGuid>4cc3d708-ccb4-4f85-839c-7f7b3d8567fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
