<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Schedules</name>
   <tag></tag>
   <elementGuidId>df69140b-0ea7-4065-b18f-07630f959c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#schedules-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='schedules-menu-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Schedules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0a3a8f7-32f9-4039-9454-85c0d3e67898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.ibexpayroll.com:8443/edge5/everestspa/schedules</value>
      <webElementGuid>67de66b7-8b74-48c3-bd50-d8a6e15f417c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedules-menu-item</value>
      <webElementGuid>6c607697-ff10-4280-a60b-983444bcf7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Schedules</value>
      <webElementGuid>32531ae0-bcfc-41dc-9a8d-f3f7bf85273d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedules-menu-item&quot;)</value>
      <webElementGuid>3603156c-6cef-48c6-8d7a-c1d439503383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='schedules-menu-item']</value>
      <webElementGuid>d151ac99-6bd8-4cb0-b455-2590fe8ef442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-navigation-list']/li[2]/a</value>
      <webElementGuid>995c7ba9-9ee0-43be-95b5-99151283df00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Schedules')]</value>
      <webElementGuid>c7784f62-7624-4978-8552-9543ec880286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>3266ece6-b97f-4aec-a939-d1ff26eb97f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info_outline'])[2]/following::a[2]</value>
      <webElementGuid>35fdbf55-d5c9-42bc-83fd-cf6f8f9a05dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Approval'])[1]/preceding::a[1]</value>
      <webElementGuid>aa669d51-3418-4827-82bf-3f60ee047866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll'])[1]/preceding::a[2]</value>
      <webElementGuid>a836ab13-3c7f-4bd3-8053-022e24ec765e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Schedules']/parent::*</value>
      <webElementGuid>d744bdc7-24dd-4fbe-a96e-d3ea624772bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.ibexpayroll.com:8443/edge5/everestspa/schedules')]</value>
      <webElementGuid>6fa18fc6-a516-4803-a2d1-abb9a96cb4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>a5f2f46e-752b-411c-b315-42f153501d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.ibexpayroll.com:8443/edge5/everestspa/schedules' and @id = 'schedules-menu-item' and (text() = ' Schedules' or . = ' Schedules')]</value>
      <webElementGuid>4d79877d-5682-4815-996c-a99675ddfd56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
