<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Department Field 1_field01Value</name>
   <tag></tag>
   <elementGuidId>b94d39b9-7b51-461d-a63c-127cb2d84323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_field01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_field01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txt_field01</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8d2d129-7da3-48a0-bfc6-4648f00ccf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c2330a8-ffd6-4236-83ca-c119c41b7d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_field01</value>
      <webElementGuid>acc7cd3e-3f76-4eb3-81a3-4759127e8667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field01Value</value>
      <webElementGuid>e16265b9-9ebd-45ff-8f2b-cd091a5591b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-valid ng-touched ng-dirty</value>
      <webElementGuid>d76b8545-7bdf-48f5-9b36-ce45e3737ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_field01&quot;)</value>
      <webElementGuid>883d440a-ed9b-4893-92ce-d217c96261b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_field01']</value>
      <webElementGuid>bdb52fd1-34f5-4c3c-8b47-434d3694629f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>66143619-5214-409f-919a-55bc1431650a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_field01' and @name = 'field01Value']</value>
      <webElementGuid>4cf04401-9f80-4be8-867d-bde5a0280f02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
