<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>c41166f4-a912-4e42-8edd-db6c8f455611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='18dfa718']/tbody/tr/td[6]/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e58a75bd-a8a4-4f88-9f71-cc9e84fe4f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edge5/everest/PayrollHistory/CancelProcessing.mr?workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=6&amp;payRunId=53ab5b90-2bdf-458e-9d40-cc7edc753727</value>
      <webElementGuid>a807109a-2877-4f1e-8d2c-9f3c72cfb5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>6680f247-6a76-48fb-bcd6-87d86228ec3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;18dfa718&quot;)/tbody[1]/tr[@class=&quot;grid_item even&quot;]/td[6]/span[@class=&quot;grid__link&quot;]/a[1]</value>
      <webElementGuid>8699e710-245f-484f-b54e-61bc6c202125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='18dfa718']/tbody/tr/td[6]/span[2]/a</value>
      <webElementGuid>b2d25917-b053-4dda-a472-d727ecf31991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>c882d50c-97b7-46e0-ab7a-fcb9680c56e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Sheet'])[1]/following::a[1]</value>
      <webElementGuid>2b7b933f-0e89-491d-bfaa-f15d8daf4cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing'])[1]/following::a[2]</value>
      <webElementGuid>9c584e8f-fd0e-4cea-a0e3-d9f807e77746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Payrun'])[1]/preceding::a[1]</value>
      <webElementGuid>6f876381-8641-4489-bc1e-a94eb34d1e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posted'])[1]/preceding::a[2]</value>
      <webElementGuid>6d9b0aac-71d3-4fd2-b752-aa7f50ed04dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>d555d3a3-dc16-4910-a7d7-111902aa06d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edge5/everest/PayrollHistory/CancelProcessing.mr?workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=6&amp;payRunId=53ab5b90-2bdf-458e-9d40-cc7edc753727')]</value>
      <webElementGuid>c2bbb708-c58c-42a7-92d9-6d166c176c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>959e57f5-3f28-4a28-bdfd-61b7594098a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edge5/everest/PayrollHistory/CancelProcessing.mr?workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=6&amp;payRunId=53ab5b90-2bdf-458e-9d40-cc7edc753727' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>c9a9a02d-a653-4e1a-8c9b-e4ca39b3507e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
