<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel_1</name>
   <tag></tag>
   <elementGuidId>8fe68c44-68db-4e24-828d-8c64b8dedd97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='13414573']/tbody/tr/td[6]/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1514d348-d3de-416b-b67e-4ce37b50dc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edge5/everest/PayrollHistory/CancelProcessing.mr?workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=8&amp;payRunId=53ab5b90-2bdf-458e-9d40-cc7edc753727</value>
      <webElementGuid>b3d430e3-a2fa-443f-9867-f7886e058153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>0e7edfb6-176a-445b-91a8-553f6605b515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;13414573&quot;)/tbody[1]/tr[@class=&quot;grid_item even&quot;]/td[6]/span[@class=&quot;grid__link&quot;]/a[1]</value>
      <webElementGuid>2fd3f542-5add-4b28-88a3-fa8ce4890bfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='13414573']/tbody/tr/td[6]/span[2]/a</value>
      <webElementGuid>cb58354e-89ac-41c8-828f-491a75c51edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>e2b46b46-2725-4b34-afc3-0d9931c9c0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Sheet'])[1]/following::a[1]</value>
      <webElementGuid>14c839f1-ecf2-45b0-8f46-425e77485d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing'])[1]/following::a[2]</value>
      <webElementGuid>0e12da57-4467-4e36-811e-3723547ddab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Payrun'])[1]/preceding::a[1]</value>
      <webElementGuid>b7b1bfc5-922c-47be-95eb-03d867ed3cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posted'])[1]/preceding::a[2]</value>
      <webElementGuid>80553f0b-67d4-40fa-859f-b3fa0812825c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>0ab730ac-2ce6-41f1-80d6-1f9797917045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edge5/everest/PayrollHistory/CancelProcessing.mr?workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=8&amp;payRunId=53ab5b90-2bdf-458e-9d40-cc7edc753727')]</value>
      <webElementGuid>f2ee7a33-4945-4a6b-8a56-a0ccf15c33a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>d1c2049f-2923-4e3b-a46c-c54a825d4423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edge5/everest/PayrollHistory/CancelProcessing.mr?workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=8&amp;payRunId=53ab5b90-2bdf-458e-9d40-cc7edc753727' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>79f36856-7a84-4b34-a1cd-1834c3cbc46c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
