<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_35</name>
   <tag></tag>
   <elementGuidId>aa574194-b51b-4c5f-8dcd-5a7d6fbd0386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.everest-progressbar__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='53ab5b90-2bdf-458e-9d40-cc7edc753727']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;35%&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>994092a9-f179-41ab-b28f-eafca71b6aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>everest-progressbar__value</value>
      <webElementGuid>5e7ad7f3-e8e3-4866-b5fa-e4013145baf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>35%</value>
      <webElementGuid>b384fa75-5d2f-4fe1-b58e-d049e266b89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;53ab5b90-2bdf-458e-9d40-cc7edc753727&quot;)/div[@class=&quot;everest-progressbar__value&quot;]</value>
      <webElementGuid>1729824a-574e-4cde-bf18-6055e68a0151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='53ab5b90-2bdf-458e-9d40-cc7edc753727']/div[2]</value>
      <webElementGuid>499721a1-146f-47c4-bad3-25fea5a7d6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing'])[1]/following::div[4]</value>
      <webElementGuid>9fae9615-71ae-402a-babc-510c9b5893eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Due Date'])[1]/following::div[6]</value>
      <webElementGuid>819c9b9a-0ead-404e-bf2d-7487c327f3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Sheet'])[1]/preceding::div[1]</value>
      <webElementGuid>d17b78c4-6d2d-46e0-ae1b-ec3967189b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[1]</value>
      <webElementGuid>5394f050-eb08-4d13-9b09-dbbb47cf47d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='35%']/parent::*</value>
      <webElementGuid>c4b8ff73-07ac-4a5f-9863-86da4f32d5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>56728ac2-e58d-4582-be63-573ea7b897cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '35%' or . = '35%')]</value>
      <webElementGuid>4aa73f36-946d-46e5-9ece-a287e03cedbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
