<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Processed</name>
   <tag></tag>
   <elementGuidId>a353073b-65ee-44b4-8316-8473ab3e0ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.payroll-history-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='0ebd7f3b']/tbody/tr/td[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Processed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e36c09e-77a7-42b0-ada7-ef11a1ff9fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payroll-history-status</value>
      <webElementGuid>6c0f0353-0435-48f7-af0c-81ffd10b1c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processed</value>
      <webElementGuid>0fbcf57a-11b5-470b-ba4a-57fc29e233a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0ebd7f3b&quot;)/tbody[1]/tr[@class=&quot;grid_item even&quot;]/td[4]/div[@class=&quot;everest-payroll-status&quot;]/div[@class=&quot;payroll-history-status&quot;]</value>
      <webElementGuid>e0496d7d-a99c-43f5-81a5-6234586d822d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='0ebd7f3b']/tbody/tr/td[4]/div/div</value>
      <webElementGuid>86458b45-6c9e-4ea2-84f8-2d6f9c76593d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Due Date'])[1]/following::div[2]</value>
      <webElementGuid>92f2e732-f93b-46c5-9ad3-44a679bb0750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[2]</value>
      <webElementGuid>4d6702a5-773d-49f4-90e1-d3d132cb6170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Sheet'])[1]/preceding::div[5]</value>
      <webElementGuid>04ee9055-a877-4dad-96a9-e0b2a9bb6128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results'])[1]/preceding::div[5]</value>
      <webElementGuid>7cf2d9ef-90fd-48aa-a9a9-52e7819518c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Processed']/parent::*</value>
      <webElementGuid>358521f9-5bb8-4749-961d-b0913bdade7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div</value>
      <webElementGuid>03ce1aa7-336d-4ef0-9206-ec6cf37d9c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Processed' or . = 'Processed')]</value>
      <webElementGuid>b3cb857c-80cb-4c81-8e40-03881da52b0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
