<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>d8081bd9-4198-45dd-85cf-b108776ecb76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-navigation-list > li.menuItem > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js-navigation-list']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00ddd23e-8d5a-46e1-81da-713f5ee577dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Edge2/Everest/Home/Index.mr</value>
      <webElementGuid>593a8158-8021-41dd-ae3c-e7bc5078b660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Home</value>
      <webElementGuid>22e8ab7c-b532-4df4-ae70-ab1dcb70c617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-navigation-list&quot;)/li[@class=&quot;menuItem&quot;]/a[1]</value>
      <webElementGuid>f756f82e-2293-4eb4-bb32-3b30b9408cde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-navigation-list']/li/a</value>
      <webElementGuid>b203e1f5-1757-4e8b-99df-c186d434f29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
      <webElementGuid>74effc32-dc14-4abf-a192-6390251bc5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info_outline'])[2]/following::a[1]</value>
      <webElementGuid>1e4b6716-4673-4242-978c-bf4fd00bf04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Entry'])[1]/preceding::a[1]</value>
      <webElementGuid>04d471c9-ddb1-48c1-aaba-34809934a1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Schedule'])[1]/preceding::a[2]</value>
      <webElementGuid>92150662-59d0-4c39-ae68-ad2f692c2f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>263bbaba-d9b1-43f4-8474-5e1b6e5d7086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Edge2/Everest/Home/Index.mr')]</value>
      <webElementGuid>db32a55e-556d-46ea-8494-809a79d843b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a</value>
      <webElementGuid>0f65c4af-8c3f-456c-be1c-ce6acd857e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Edge2/Everest/Home/Index.mr' and (text() = ' Home' or . = ' Home')]</value>
      <webElementGuid>b48e9dd3-e4d3-4b1d-85ca-6ec7ff4b9b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
