<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Schedule</name>
   <tag></tag>
   <elementGuidId>12e93308-c8f3-468b-9e91-0afd6636439d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frequency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'frequency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#frequency</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>3b7ddb31-f3b3-490b-aa0b-99a1208d3add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>4b287dca-f868-4e30-aaae-63f3eb28a9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>7ae20f64-ec0e-4a2f-99ee-79aa3a118b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DefaultFrequencyObjId</value>
      <webElementGuid>adc8eea6-a6d8-4bb1-bd0f-8d119e8f274b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>cbab8ce2-4f5e-4481-b9f1-47f953a71058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frequency</value>
      <webElementGuid>72a29ebe-dfaa-4020-b7fb-73ae30747382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3865f487-9d22-42a9-9ffd-629bdc6595af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>636aa224-250a-4782-bcc4-d04c8c9346b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select Schedule --</value>
      <webElementGuid>97b2f875-a94a-4809-8728-c8e8f7a246cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Schedule</value>
      <webElementGuid>0018446a-e74e-4b9b-967f-bdc81e8ebea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>--Select Schedule --</value>
      <webElementGuid>5d336956-ade8-4426-82a8-102d09f02a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-041b19ae70781f0af9df7a5fe525a1ba</value>
      <webElementGuid>8db7140d-86c7-4e01-ba4b-a79c7bbd4f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'frequency']</value>
      <webElementGuid>af41d7e7-a689-49f1-b331-94ca5ec29015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'frequency']</value>
      <webElementGuid>f83e0b4d-cc24-4783-b156-22b429f0a969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'frequency' and @title = '--Select Schedule --' and (text() = 'Schedule' or . = 'Schedule')]</value>
      <webElementGuid>2f3bb9ee-2aa0-4a4b-a012-96ce0d92ad6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'frequency' and @title = '-- Select Schedule --' and (text() = 'Schedule' or . = 'Schedule')]</value>
      <webElementGuid>8dde267f-88fa-4ef9-82a7-a4a82cb3e747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
