<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applies to</name>
   <tag></tag>
   <elementGuidId>aeb15cb0-16d9-4ba9-977d-f1e10bd07e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isAppliedToAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'isAppliedToAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Applies to:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bf7a4f0-1f55-4948-8b2d-f8ba79788ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>907fa127-d540-4a46-bf51-ce8726f2c218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isAppliedToAll</value>
      <webElementGuid>2c4cbac6-b888-4a15-88f3-1029485b70bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>IsAppliedToAll</value>
      <webElementGuid>140faf48-fbbf-455c-804c-c7e7d1f87424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-checkbox ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7ea13a06-f9f7-49cb-b5f4-45839f4fe6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Applies to</value>
      <webElementGuid>08e40293-6963-43f2-99b0-c3bdcfbc3f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e2adbcc22a1f1dadda78e6acc2984fe</value>
      <webElementGuid>a33c1924-4398-40bb-9ab8-6a3a8c23987d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'isAppliedToAll']</value>
      <webElementGuid>a060d41e-fe5d-4728-b60f-e771e6b2aa98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'isAppliedToAll']</value>
      <webElementGuid>bce7dfe7-caf3-4a1c-ac19-e600abf91387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isAppliedToAll' and (text() = 'Applies to' or . = 'Applies to')]</value>
      <webElementGuid>dad75d09-27a3-44be-9130-c3ff863a20ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
