<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Allow</name>
   <tag></tag>
   <elementGuidId>aefaaa12-5abd-47e8-b6f6-6cee878385a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isOverrideAllowed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'isOverrideAllowed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Allow:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>026a2ef2-a764-484b-aa1c-b9147dd03243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>47caaec8-b117-4032-b122-1e9fd016d4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isOverrideAllowed</value>
      <webElementGuid>28b2b4a9-502a-4d05-98a9-c9bb501c82a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>IsOverrideAllowed</value>
      <webElementGuid>62f0eb6e-808a-42f6-9bff-5ebc7d01796a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-checkbox ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7012d32e-05d8-423e-8145-a06b8a7cbfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow</value>
      <webElementGuid>a0a696a8-52cf-4b70-90fd-9c312cf29010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-070ad9000a203c2c0deccf2912c575df</value>
      <webElementGuid>a88f0a7c-9e33-4b21-ba43-c0aac97edd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'isOverrideAllowed']</value>
      <webElementGuid>a8e4ec70-cb27-4f65-9e58-b1e0566f15f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'isOverrideAllowed']</value>
      <webElementGuid>386c4450-6b2c-4926-84af-b97af0485b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isOverrideAllowed' and (text() = 'Allow' or . = 'Allow')]</value>
      <webElementGuid>3a8a46f1-c4b6-480a-8379-c2ede01c7cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
