<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nameFrench</name>
   <tag></tag>
   <elementGuidId>8052156b-f227-46bf-996d-e21c296315b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameFrench</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nameFrench']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nameFrench</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62ea9637-596c-4bee-8d0b-d9fef4e7ba39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13cc5399-8b7c-4ce9-9b15-75979491bee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>8e22558e-b8fc-49ac-b82b-9d0f684e50bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>NameFrench</value>
      <webElementGuid>c20f7845-a377-459d-a4c1-f69d8f03a93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9014396e-f470-4cbf-b41d-5a32db262e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>1611ab5e-43a7-454a-8066-6b61bbd54874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b2d50dbd89a59c761b01381853be16aa</value>
      <webElementGuid>503988e7-5ceb-45e6-b930-fa6099ff947d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>fa5b8a1d-0090-4a40-b54f-791f3f6554b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>67f9272e-3e00-4c9b-99f2-c35ba815080e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameFrench' and (text() = 'nameFrench' or . = 'nameFrench')]</value>
      <webElementGuid>1cc7918b-47a8-4ff2-964c-be8fbaf77864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
