<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description</name>
   <tag></tag>
   <elementGuidId>6400720e-95ed-45b1-9360-8f689e19d740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descriptionEnglish</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'descriptionEnglish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f093302c-a849-4015-ac17-fa981a153e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c60bbfe7-6d56-4fba-953a-a226fa935b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionEnglish</value>
      <webElementGuid>4dceca19-791f-4c2f-b680-19ec48ea9888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DescriptionEnglish</value>
      <webElementGuid>a5035512-facd-4794-82fd-f2ba895b687d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c726fe2a-fd83-4949-8f08-503a82b5e6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>a1eeb0ab-d486-4d87-b042-2a2c842981cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e53d8606c1bcb0a98aafdcb52c7855b9</value>
      <webElementGuid>ed0a356d-d05e-4909-9246-9f352db69e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionEnglish']</value>
      <webElementGuid>b75200fa-65e7-406e-bf25-1a6f3fabc28e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionEnglish']</value>
      <webElementGuid>a2bb078f-96bf-406c-8f55-0dbc52dd4617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionEnglish' and (text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>b83256d6-d034-4bd4-8fa7-9a82635d85b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
