<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_descriptionFrench</name>
   <tag></tag>
   <elementGuidId>90e17dc2-00cc-4913-9586-09456bbd24ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#descriptionFrench</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'descriptionFrench']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#descriptionFrench</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b800dafa-287e-4f40-b3ba-0a6c19f6353f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a617c7cf-0656-467b-8d0c-15f5c8ef21ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionFrench</value>
      <webElementGuid>8f9dbdce-0661-4093-addf-2f24b3d18d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DescriptionFrench</value>
      <webElementGuid>3eed6942-c1c6-4785-ab9c-bd4c5a66e4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>aa6e2d2d-4622-4fe0-8753-98cba5d0dbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>descriptionFrench</value>
      <webElementGuid>37a6dc68-9295-4202-8496-cfc575518fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-649358ba2d05fbd009bd6d6be69ad53d</value>
      <webElementGuid>35a26391-a534-4f64-af53-a5ba1e6c3b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionFrench']</value>
      <webElementGuid>23032d0b-e329-483e-b59a-c185d0c3d53c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'descriptionFrench']</value>
      <webElementGuid>ac846674-4015-4ed6-8daa-b8ff2c3c8aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'descriptionFrench' and (text() = 'descriptionFrench' or . = 'descriptionFrench')]</value>
      <webElementGuid>56eb9afe-8d3e-4483-9b58-a0e8d5175958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
