<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_defaultFormula</name>
   <tag></tag>
   <elementGuidId>aec39057-e4bf-4f0f-8596-d514788a1c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#defaultFormula</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'defaultFormula']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#defaultFormula</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>79685e89-fa03-4bed-b57b-c4bfed77eaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>dc1ec70a-60ed-4995-b6bb-508d6536738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>c5865dbf-d5a7-4897-9626-ca45569b1b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d68c642f-a379-4158-8fc7-ac701e2b8493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>113a0997-8853-48fa-aa1d-14da6172a23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b4d11e64-a787-454f-a2eb-1e71049daaed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DefaultFormula</value>
      <webElementGuid>00dc6e6c-77dc-4650-a28f-31b744ccc627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5256e7a0-7d8f-4d2c-b58f-d56290506745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>d3dd9509-c28b-431d-bd61-cfcec2cc41b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>fd7ad340-287b-4c88-85f7-e163a3a0e2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-287cb90c8af5d1c88243b2405e542df6</value>
      <webElementGuid>74c5ef5f-5ddd-4097-bf61-698362f4b711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'defaultFormula']</value>
      <webElementGuid>a1b355ad-127f-419f-8bf0-6c02f7d87e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'defaultFormula']</value>
      <webElementGuid>23251e42-2fc5-4d5f-a600-c5473d614c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'defaultFormula' and @id = 'defaultFormula' and (text() = 'defaultFormula' or . = 'defaultFormula')]</value>
      <webElementGuid>8016fc92-8361-40d4-8e0f-17904705e5da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
