<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Filter_processpayroll</name>
   <tag></tag>
   <elementGuidId>ff191251-7a43-48a3-93f6-4abb482fc9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#processpayroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='processpayroll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Calculate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0e88652-b732-4946-b969-45498dab2284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a98ee873-dbb0-42e8-ad32-de87f1d4f7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>cf390677-ee8c-4058-bb9b-e081cebd0f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>processpayroll</value>
      <webElementGuid>810be7d8-108b-4dac-ba16-e426ac0c8886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-button link-button--primary u-nowrap u-m-bottom--half</value>
      <webElementGuid>24830c1f-c9b6-4bba-92ac-e3d9c30aa34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>This button has been renamed from Submit to Calculate to more accurately reflect it's function - calculating the payroll results for your review</value>
      <webElementGuid>a60cf4d8-7554-47f9-8c0f-b7f4cfc20797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;processpayroll&quot;)</value>
      <webElementGuid>0ee23fb7-09d2-4dd4-ae51-f992f0c18bf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='processpayroll']</value>
      <webElementGuid>059b44e8-152c-4d88-add7-46e38ac9ab2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optionsPanel1']/div/input[3]</value>
      <webElementGuid>c70b5800-2d66-4c3c-bde8-f399d05d8859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>b93221e5-59a9-4578-a051-f109b064d4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'processpayroll' and @title = concat(&quot;This button has been renamed from Submit to Calculate to more accurately reflect it&quot; , &quot;'&quot; , &quot;s function - calculating the payroll results for your review&quot;)]</value>
      <webElementGuid>8b1a87f4-d687-4088-a9cd-9f70597164e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
