<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ann BC Org</name>
   <tag></tag>
   <elementGuidId>25c39f98-e8ad-4411-bf2e-25c305e892d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='CloseDialog(0);'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ann BC Org&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7cdf4d6d-56b8-4d5f-af34-a1d795383ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CloseDialog(0);</value>
      <webElementGuid>1dd08ddf-5ea3-4951-89a8-94daafe9cb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=5dce93b4-174e-439e-97ad-1892817d900d</value>
      <webElementGuid>b3f33897-d584-44ee-b93c-6f99be8bb9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ann BC Org</value>
      <webElementGuid>8410297d-f793-4858-bde0-9913586ad1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridOrganizationDialogResults&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[2]/a[1]</value>
      <webElementGuid>ed987d41-f356-4e36-8a31-2d5dd5cf8018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='CloseDialog(0);'])[6]</value>
      <webElementGuid>fd0ac526-ab01-4958-96d7-e3e24d6ed292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridOrganizationDialogResults']/tbody/tr[3]/td[2]/a</value>
      <webElementGuid>18c27741-652d-4fc0-90c0-0718c9ece421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ann BC Org')]</value>
      <webElementGuid>c660e28b-df86-470c-a1e4-e9af81020084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APC-bc'])[1]/following::a[1]</value>
      <webElementGuid>591df40f-3982-4954-8fa4-fe27bd035acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AAA Test Organization'])[1]/following::a[2]</value>
      <webElementGuid>3f037fb5-0fe6-4056-8fd9-0a13909b426a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP7'])[1]/preceding::a[1]</value>
      <webElementGuid>1c44b5a3-8b9e-42cd-8c1b-f2e03d613d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ann BC Org']/parent::*</value>
      <webElementGuid>4c33f7a3-22ae-497f-80bf-a774cd11c705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=5dce93b4-174e-439e-97ad-1892817d900d')])[2]</value>
      <webElementGuid>5e82014e-777c-4bd5-bfe7-9af40d68daca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/a</value>
      <webElementGuid>d246cff7-2571-4c81-942b-de6751db46de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=5dce93b4-174e-439e-97ad-1892817d900d' and (text() = 'Ann BC Org' or . = 'Ann BC Org')]</value>
      <webElementGuid>5112d4c4-4463-4489-8371-1be42d5a9203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
