<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anns Test Org</name>
   <tag></tag>
   <elementGuidId>92b5ffbc-32db-4927-8c15-6967ecb08ffd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ann's Test Org&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>468dda63-fd45-4717-837a-c3073b8e2875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CloseDialog(0);</value>
      <webElementGuid>29fd9ea3-53da-4dc6-b49f-4cfcfa38aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6</value>
      <webElementGuid>22e1041d-e07d-4eee-b9a5-e910957be818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ann's Test Org</value>
      <webElementGuid>dbe98c25-fbb1-4fd8-b005-915020241185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridOrganizationDialogResults&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[1]</value>
      <webElementGuid>4d3fa8ca-5a58-4949-9290-341b7f8ad19e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      <webElementGuid>039de89f-3a22-4879-a7f9-920fceea498d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridOrganizationDialogResults']/tbody/tr[4]/td[2]/a</value>
      <webElementGuid>5e788156-50f9-4c2e-af46-95ceddc13bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP7'])[1]/following::a[1]</value>
      <webElementGuid>98d64857-0e31-4fa4-93b3-fd14c55eef14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ann BC Org'])[1]/following::a[2]</value>
      <webElementGuid>bc7bfe36-f94e-4e71-86fa-e4cc9b71b045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP-2'])[1]/preceding::a[1]</value>
      <webElementGuid>8d704395-3477-4df0-a077-3b3cac9bc09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6')])[2]</value>
      <webElementGuid>b45e4337-92f5-4367-836f-940082e58810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a</value>
      <webElementGuid>5214f9e0-e266-464e-a729-bc8ef3009259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/main/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6' and (text() = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;) or . = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;))]</value>
      <webElementGuid>a54ff3c8-7da3-48c8-8960-ea12a725b355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
