<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_swap_horiz</name>
   <tag></tag>
   <elementGuidId>dae607c3-b212-44c3-b673-f84928f9e4fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='contextSwitch--navheader']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contextSwitch--navheader > i.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;swap_horiz Switch&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0ce34164-4867-44b7-9d45-c48b2b174f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>b5275466-d4f8-4848-852f-84571516092a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swap_horiz</value>
      <webElementGuid>16eb1d06-1a4c-4072-ba75-d5745fe62dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contextSwitch--navheader&quot;)/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>0bf9aa0e-c7f5-4a17-a94c-d0042ad6d903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='contextSwitch--navheader']/i</value>
      <webElementGuid>0b39eb91-e37a-4cbd-ad89-20b494370525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='exit_to_app'])[1]/following::i[1]</value>
      <webElementGuid>154ecc7c-0871-44d4-b87c-8c44202566a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='description'])[1]/preceding::i[1]</value>
      <webElementGuid>4cc36b41-05a0-478f-a69d-5dfbbf7ad10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>8d42c68e-e5e7-40d7-b080-2c7d0a0378c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'swap_horiz' or . = 'swap_horiz')]</value>
      <webElementGuid>ad2823b7-a935-4b8a-b509-0a9d6a0f9088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
