<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_chevron_leftchevron_left</name>
   <tag></tag>
   <elementGuidId>68ec5b57-1658-46f3-b02b-465ef4f0b941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[32]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.prev-period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;chevron_left chevron_left&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0459db54-bb96-4bb6-9514-8d871726e7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff17a4fc-7b6e-4ff1-b8fb-11007bea5cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prev-period</value>
      <webElementGuid>20c6e17b-0e34-4b62-8825-3d61916eac16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>chevron_leftchevron_left</value>
      <webElementGuid>edeba7c9-520b-4cb8-8baa-9a8402bc2c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/fw-datepicker[@class=&quot;fw-datepicker&quot;]/fw-datepicker-month-view[@class=&quot;fw-datepicker-month-view ng-star-inserted&quot;]/fw-datepicker-header[@class=&quot;fw-datepicker-header&quot;]/button[@class=&quot;prev-period&quot;]</value>
      <webElementGuid>d5715755-7d40-41f2-873d-b127812ee6df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[32]</value>
      <webElementGuid>d11f943b-9092-4143-82c3-03bad8b1cae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/fw-datepicker/fw-datepicker-month-view/fw-datepicker-header/button</value>
      <webElementGuid>4d8f0e34-88cd-4839-b928-714b22c912c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/following::button[1]</value>
      <webElementGuid>db8a763c-034b-48a3-979f-84eb2e9b0a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stay'])[1]/following::button[2]</value>
      <webElementGuid>163792f6-a3f9-46f3-981d-25df46052e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-datepicker-header/button</value>
      <webElementGuid>c7f30bdf-3c91-470c-bdc5-4153b62bbd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'chevron_leftchevron_left' or . = 'chevron_leftchevron_left')]</value>
      <webElementGuid>9e5a78c7-447a-44db-89d4-45b3ef47a71d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
