<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Toggle Selection of All Rows_selectAll</name>
   <tag></tag>
   <elementGuidId>05f5e43e-93cc-40c6-89e1-691302323da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Toggle Selection of All Rows&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>990306e4-7a17-482d-9bb7-04838bb15592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>971e3af5-8cdf-4866-ba88-6227468b1179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectAll</value>
      <webElementGuid>c3ec97cc-62e9-4a4c-86a7-cff889d2deb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectAll&quot;)</value>
      <webElementGuid>d0ade26f-5ad1-4aef-b08e-48768c3421ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectAll']</value>
      <webElementGuid>33d39e80-d4ac-4c3c-b68b-7aff7b03f7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-daily-approval-table/div/div/div[2]/input</value>
      <webElementGuid>e9ae3322-55f7-4eb6-8074-32efc85b8f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectAll']</value>
      <webElementGuid>512b25dd-e574-447c-986c-4b1bf1115fbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
