<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anns Test Org</name>
   <tag></tag>
   <elementGuidId>b6aaced6-b0eb-4053-bdff-05cabeda3340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ann's Test Org&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91e6e147-584b-4333-a652-9302fd6f9e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CloseDialog(0);</value>
      <webElementGuid>38951919-8507-4089-8945-985285bbc55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edge2/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6</value>
      <webElementGuid>72f79766-963e-4431-8ccc-cb17808bd894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ann's Test Org</value>
      <webElementGuid>4a200f92-212f-4cd6-bb54-8acb6f496683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridOrganizationDialogResults&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[1]</value>
      <webElementGuid>146f4739-8d1b-495b-b1a3-f0487ec8c34a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      <webElementGuid>da131148-3e98-4442-9c1c-759b29d8f47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridOrganizationDialogResults']/tbody/tr[4]/td[2]/a</value>
      <webElementGuid>b7f10456-89c7-43c5-8c43-a860ecdc2b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP7'])[1]/following::a[1]</value>
      <webElementGuid>dbb32bb5-aff4-4687-9d57-6337470bc9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ann BC Org'])[1]/following::a[2]</value>
      <webElementGuid>32547673-3628-40d3-afd5-4c58ef0e3207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP-2'])[1]/preceding::a[1]</value>
      <webElementGuid>07a42175-db9b-4dc1-921f-26ad8c0079c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/edge2/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6')])[2]</value>
      <webElementGuid>8aeb372e-3437-4be5-8768-ed8bd6f2e525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a</value>
      <webElementGuid>9bfb5a0c-cef8-4e3f-a480-a680bddd597b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edge2/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6' and (text() = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;) or . = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;))]</value>
      <webElementGuid>eb14e4db-efa1-4981-a8f2-62606c4fe6cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
