<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Schedules</name>
   <tag></tag>
   <elementGuidId>d7112bc4-7058-4ef9-8981-79df00f75f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js-navigation-list']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#js-navigation-list > li.menuItem > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Schedules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7a13d92-dfeb-4c48-a35e-711127529401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.ibexpayroll.com:8443/edge2/everestspa/schedules</value>
      <webElementGuid>bb2472a3-7805-46ed-a882-85b806ea3500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Schedules</value>
      <webElementGuid>279ff457-2cea-47e0-a42a-381fa4b67c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-navigation-list&quot;)/li[@class=&quot;menuItem&quot;]/a[1]</value>
      <webElementGuid>42942cda-daa3-4841-9d4b-ab50a4661377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-navigation-list']/li[2]/a</value>
      <webElementGuid>98142d71-de3d-4636-8071-e1a9d4d84fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Schedules')]</value>
      <webElementGuid>07b778d3-6c46-43e3-a639-acfc5a52955c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>c24320aa-d267-4a7e-97a7-f44d96b37f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info_outline'])[2]/following::a[2]</value>
      <webElementGuid>5327f0d9-75f7-41b7-be94-f9df1755a42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Approval'])[1]/preceding::a[1]</value>
      <webElementGuid>62048d38-0f48-488f-bf34-2082545216ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll'])[1]/preceding::a[2]</value>
      <webElementGuid>92ae6c03-e399-4632-8e70-46d7544d2f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Schedules']/parent::*</value>
      <webElementGuid>d5e5bc5e-f745-4b08-896c-6c66b8bc399a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.ibexpayroll.com:8443/edge2/everestspa/schedules')]</value>
      <webElementGuid>7eab051a-f4ea-4849-a72a-64d630d50db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>515f5da7-4bb9-4c10-a753-3ed706ab7abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.ibexpayroll.com:8443/edge2/everestspa/schedules' and (text() = ' Schedules' or . = ' Schedules')]</value>
      <webElementGuid>dc50185e-96a9-416f-895b-15df8c3ef5cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
