<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_0.00_1_2</name>
   <tag></tag>
   <elementGuidId>b74ce08a-dd62-4d2a-90e7-d6ddc4c68871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PayrollTotal13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='PayrollTotal13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PayrollTotal13</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>dba009de-28ae-4be8-b4e5-46c76e85e296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EBDDataCell</value>
      <webElementGuid>8d950143-8d0b-4daa-8566-11e80aea8cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PayrollTotal13</value>
      <webElementGuid>ca654ec3-69be-4c5a-af93-0147f0c474f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>9e70d3a3-488c-4581-9665-42bd9dafe143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PayrollTotal13&quot;)</value>
      <webElementGuid>94ea2a58-5eb5-4bd0-a99e-cd379c0de43a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='PayrollTotal13']</value>
      <webElementGuid>28215313-ca90-4980-b648-9b6dcdf318d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='inputSheet']/tbody/tr[31]/td[13]</value>
      <webElementGuid>48b2d3f3-5c5a-4751-acc4-13a25e8202c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$35.51'])[3]/following::td[54]</value>
      <webElementGuid>6b38666f-9782-4e28-9d45-f1a40ee4bed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$35.51'])[2]/following::td[59]</value>
      <webElementGuid>82fe1fb9-5479-4056-9b5a-dfae719478b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::td[18]</value>
      <webElementGuid>293df64e-8098-4039-acd7-2a7a361451da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::td[18]</value>
      <webElementGuid>31a961fa-8597-4211-a80e-c71378b2c9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[31]/td[13]</value>
      <webElementGuid>8e91e110-6459-4088-a0d5-6a186af6763d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'PayrollTotal13' and (text() = '0.00' or . = '0.00')]</value>
      <webElementGuid>4c374a58-e6b3-40cb-81e6-437fa6183b29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
