<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Full Flow of TOR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5d2a1bf1-6525-4d75-882b-fe96688636d2</testSuiteGuid>
   <testCaseLink>
      <guid>a84d08ff-54eb-49c9-83bd-432b19f4d4cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR_Shared/TOR-001_SH_Login_EE and Navigate to TOR</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9398a1f6-4c7a-45f6-abac-dab0f7167bc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Request Submission/Submit TOR Request - Valid Data/TOR-002_Submit TOR Request - Valid Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d537bbd5-7d65-4217-b063-ba829ac18d49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c6d101f-fc32-48b1-9c52-7b5d36b22128</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc42e311-351e-4c68-929c-2fa9cc34a5fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>485e55c4-cf7d-4c6d-ae11-28a120cd0b85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Request Submission/Submit TOR Request - Valid Data/TOR-002a Verify Submited TOR Request - Valid Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>96f0306b-b8b6-4e78-a138-c038ffef79be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Request Submission/Submit TOR Request - Invalid Dates/TOR-003_Submit TOR for period with no schedule</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d537bbd5-7d65-4217-b063-ba829ac18d49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c6d101f-fc32-48b1-9c52-7b5d36b22128</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc42e311-351e-4c68-929c-2fa9cc34a5fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc2ca42b-6b0d-417b-85df-90b2c9c20085</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ce7040a-cceb-492d-8dac-158821a6d731</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Request Submission/Submit TOR Request - partial Day with valid date/TOR-004_Partial day</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d537bbd5-7d65-4217-b063-ba829ac18d49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c6d101f-fc32-48b1-9c52-7b5d36b22128</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc42e311-351e-4c68-929c-2fa9cc34a5fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae2ae23d-7183-4f00-8dec-201b7695e619</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d682c3c5-1db8-479e-a384-f167bb43044d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b09a060c-ec64-4714-97e0-e1266a476265</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Request Submission/Submit TOR Request - partial Day with valid date/TOR-004a_Verify Partial day Hours</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6eddcd1b-af18-42a0-a1dd-b08030b7f838</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af931215-1102-4bbe-a279-dd9ba1a05629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6bfb57b-9171-4597-8c11-f177de8ff9f7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
