<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Validate new feature</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8ecdc50b-a519-40ee-bf12-d9ede685a905</testSuiteGuid>
   <testCaseLink>
      <guid>a523d12e-22b4-4463-ac25-91aab39df0b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR_Shared/TOR-001a_SH_Login_Manager and navigate to Review TOR</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>70bf3aca-3aa5-4e55-aa79-6ab699f1dd43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Manager Approval/Validate new feature/TOR-005_Confirm_ViewDates_dropdown</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>464ebc02-996c-44d3-9e56-250a21f36b84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Manager Approval/Validate new feature/TOR-006_Validate Submitted date filter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47cc4e3a-baeb-49c9-9ce0-731e29049621</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f22b04b-6711-4e81-ab4a-17773395df5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b8500f9-cb98-486c-ae2d-78edb177153e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9e719a0-3bd4-4b62-a033-cd1f7bb9dc7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ade35581-eccb-4406-93a5-851484af796f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Manager Approval/Validate new feature/TOR-007_Validate Requested date filter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47cc4e3a-baeb-49c9-9ce0-731e29049621</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f22b04b-6711-4e81-ab4a-17773395df5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b8500f9-cb98-486c-ae2d-78edb177153e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9e719a0-3bd4-4b62-a033-cd1f7bb9dc7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c36cb205-20b2-4be6-b48d-39cf3da7e717</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5252187c-0d9a-4d9e-b762-21f452324992</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Manager Approval/Validate new feature/TOR-008_validate new columns</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4af137c1-2686-45bf-be94-3d60af76ecff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TOR/TOR Manager Approval/Validate new feature/TOR-009-Confirm Deaprtment filter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
