<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_2,401.50</name>
   <tag></tag>
   <elementGuidId>3ba8c1a6-478f-4775-bc7f-d9363daf66ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total-hours</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='total-hours']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#total-hours</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>b52ca066-f5a9-4f5b-806a-90c46592f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total-hours</value>
      <webElementGuid>63a0220c-31f6-4f80-920d-6292462a8f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2,401.50</value>
      <webElementGuid>36632a00-69ca-4438-8479-f62798d52659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total-hours&quot;)</value>
      <webElementGuid>98409b2f-4ec9-4adf-8139-358761ea7021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='total-hours']</value>
      <webElementGuid>3b506caa-b26f-42d8-a7d2-ec9bb59f7e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::th[4]</value>
      <webElementGuid>0425cb54-ec5e-4582-a64b-f261b3546a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/following::th[5]</value>
      <webElementGuid>5e9c153e-35a0-440a-a488-dd953711c665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand row'])[1]/preceding::th[1]</value>
      <webElementGuid>71544918-2d8b-4fbc-b5c0-be5bed36feae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balsam House'])[1]/preceding::th[1]</value>
      <webElementGuid>343f42cf-3211-4d6b-b5f4-a71a2f2f519a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/th[4]</value>
      <webElementGuid>4b0a6417-a648-4cbe-b201-7525240dd223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'total-hours' and (text() = '2,401.50' or . = '2,401.50')]</value>
      <webElementGuid>eb9c0a09-d65a-48d1-92ba-ee38c86f5d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
