<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Approve   SetupSimpleDialog(ApproveDialog_ffd324</name>
   <tag></tag>
   <elementGuidId>8b0bbb1d-0113-440d-a7f8-40c167d44a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Approve</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Approve']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Approve&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e84eeee8-a80a-4b0b-9e00-20ef0c04ed5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>87bb7ec2-4c7b-4621-94ec-c6ed4c0adf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>039c45b7-86d4-4257-b2e1-9eccdc10c9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> link-button</value>
      <webElementGuid>e83aaf50-2e84-4097-a165-af450e82a454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve   SetupSimpleDialog('ApproveDialog', 'Negative Pay Warning', 'Approve', '/Edge5/Everest/PayrollResults/RunNegativePayWarningDialog.mr?payrunId=53ab5b90-2bdf-458e-9d40-cc7edc753727&amp;workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=11', '', 'autoOpen:false,width:640,height:310,modal:true,draggable:false,resizable:false');   </value>
      <webElementGuid>d81e03b8-5c12-497f-a5f2-7eb18eeaf624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Approve&quot;)</value>
      <webElementGuid>acbf4ffd-b2f2-44e3-84d3-7cda3f4960fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Approve']</value>
      <webElementGuid>f4fa6185-a212-4e1d-988c-86ade59e932f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPayrollResultsIndex']/a[14]</value>
      <webElementGuid>083bccbe-91c6-4f6d-afc6-5756fad64a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,543.65'])[1]/following::a[1]</value>
      <webElementGuid>72012b4b-9658-4edd-a209-91617686e0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Totals:'])[1]/following::a[1]</value>
      <webElementGuid>b4222c46-5cf7-4a7d-b681-0a827dfc18fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[1]/preceding::a[1]</value>
      <webElementGuid>2bd3ba6e-feb7-4f14-963b-89c73ae42f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='clear'])[1]/preceding::a[1]</value>
      <webElementGuid>678d533e-1952-4296-90fc-49ee23c019cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approve']/parent::*</value>
      <webElementGuid>06afcc11-bf0a-4b7b-9a52-fcb403524261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>fc34c32c-8eff-423e-a3b7-4aee832e79f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[14]</value>
      <webElementGuid>3ec2a339-b2a2-484e-9279-c1058bd07bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'Approve' and (text() = concat(&quot;Approve   SetupSimpleDialog(&quot; , &quot;'&quot; , &quot;ApproveDialog&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Negative Pay Warning&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Approve&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;/Edge5/Everest/PayrollResults/RunNegativePayWarningDialog.mr?payrunId=53ab5b90-2bdf-458e-9d40-cc7edc753727&amp;workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=11&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;autoOpen:false,width:640,height:310,modal:true,draggable:false,resizable:false&quot; , &quot;'&quot; , &quot;);   &quot;) or . = concat(&quot;Approve   SetupSimpleDialog(&quot; , &quot;'&quot; , &quot;ApproveDialog&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Negative Pay Warning&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Approve&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;/Edge5/Everest/PayrollResults/RunNegativePayWarningDialog.mr?payrunId=53ab5b90-2bdf-458e-9d40-cc7edc753727&amp;workflowInstanceId=43381b6a-439e-4449-a71f-1780752332dd&amp;workflowInstanceStepId=11&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;autoOpen:false,width:640,height:310,modal:true,draggable:false,resizable:false&quot; , &quot;'&quot; , &quot;);   &quot;))]</value>
      <webElementGuid>0ff24633-0ff0-470d-ac05-1a89d3f6359e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
