<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PAYROLL</name>
   <tag></tag>
   <elementGuidId>fe1e70cc-9f6f-4edd-ab37-9e8808d6068a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.menu-item.ng-tns-c1902129880-5.ng-star-inserted.router-link-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'PAYROLL')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PAYROLL&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>609ebc9d-b805-4976-9fe3-5f9afaf13dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item ng-tns-c1902129880-5 ng-star-inserted router-link-active</value>
      <webElementGuid>534ec3c1-4d27-45ac-a9b1-c3c03cc59cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.ibexpayroll.com:8443/main/Everest/Payroll/Index.mr</value>
      <webElementGuid>41cfdf7d-5d3d-48f0-93ca-a6c60a7e55f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PAYROLL </value>
      <webElementGuid>3313e4e5-8de4-4b02-8b1e-1a42cfca1339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;material-icons--loaded&quot;]/spa-app[1]/fw-framework-body[1]/fw-content[1]/main[1]/fw-navigation-menu[@class=&quot;ng-star-inserted&quot;]/ul[@class=&quot;navigation-list&quot;]/li[@class=&quot;ng-star-inserted&quot;]/fw-menu-item[@class=&quot;navigation-list__link ng-tns-c1902129880-5 ng-star-inserted&quot;]/a[@class=&quot;menu-item ng-tns-c1902129880-5 ng-star-inserted router-link-active&quot;]</value>
      <webElementGuid>afdb24b4-1089-4a11-82ce-3e22c9cd5e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PAYROLL')]</value>
      <webElementGuid>91663fe8-8a66-4f8b-8fd3-197d771372dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAILY APPROVAL'])[1]/following::a[1]</value>
      <webElementGuid>cc1eba7b-aad7-4aa1-a3a3-b2a19a9772dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHEDULES'])[1]/following::a[2]</value>
      <webElementGuid>1baa1d2e-5e80-4c68-8cc1-a9e62c52e6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORTS'])[1]/preceding::a[1]</value>
      <webElementGuid>c7f542cc-90e4-4eea-b6c3-9d17c09f9013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROE'])[1]/preceding::a[2]</value>
      <webElementGuid>a495fddf-3567-4b10-8531-172bba6b4b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAYROLL']/parent::*</value>
      <webElementGuid>df772834-62af-4163-a880-466ef9c2f11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.ibexpayroll.com:8443/main/Everest/Payroll/Index.mr')]</value>
      <webElementGuid>5a00994e-3060-4fea-8447-9f059a3d32ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/fw-menu-item/a</value>
      <webElementGuid>d46e0982-082e-4c36-b749-92a21a5b1768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.ibexpayroll.com:8443/main/Everest/Payroll/Index.mr' and (text() = ' PAYROLL ' or . = ' PAYROLL ')]</value>
      <webElementGuid>76a09f56-375d-45cc-85c2-b1c365a03110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
