<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_employeeNotes</name>
   <tag></tag>
   <elementGuidId>77458978-44ba-40cf-b25a-3e202393df4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employeeNotes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='employeeNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Notes&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>77757ec3-5221-4875-8d44-31a188ca7cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeNotes</value>
      <webElementGuid>8c38b7a9-21d4-41ac-b1c2-480142d4831f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>23356674-bdc1-47ed-aa57-45e42c1aa603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>EmployeeNotes</value>
      <webElementGuid>584435ce-2936-4bce-b953-2945d478dd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>cd88f426-73ef-4f14-b968-a2419b125237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2048</value>
      <webElementGuid>b10fe3ec-d416-40fe-a6a4-6baeb755c586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeNotes&quot;)</value>
      <webElementGuid>a645ec57-2848-45d5-a9cc-b34e3b15fad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='employeeNotes']</value>
      <webElementGuid>aa9c606a-1d47-471b-8150-b290c8050158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>bfb1c737-5f22-40ff-b4b7-ece9f9b0ec5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'employeeNotes']</value>
      <webElementGuid>de861fcf-2cdf-4e28-82e7-7f47a20c6137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
