<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table-input sheet</name>
   <tag></tag>
   <elementGuidId>7b24954f-d803-481a-86c5-bfe053ccd985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='inputSheet']/tbody/tr/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.EBDHeading.earningHeadingBackground</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Earnings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>cfd15e77-bd62-4a2e-8d0d-49328a3d7caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EBDHeading earningHeadingBackground</value>
      <webElementGuid>3d1000a2-c55b-4a6d-96db-881c8b2052de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>379f9709-f636-4ef0-8088-f1890c530b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Earnings</value>
      <webElementGuid>b4e2566d-6207-4b55-9422-db623120f1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputSheet&quot;)/tbody[1]/tr[1]/th[@class=&quot;EBDHeading earningHeadingBackground&quot;]</value>
      <webElementGuid>82c6f73b-fddd-4a47-ad41-5c5c906e4518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='inputSheet']/tbody/tr/th</value>
      <webElementGuid>4ce4ee26-2844-44b0-99aa-cf53fe020e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll Totals:'])[1]/following::th[1]</value>
      <webElementGuid>bb1c51c2-db16-4d08-887a-c44984acab9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page Totals:'])[1]/following::th[1]</value>
      <webElementGuid>a07dc681-5db5-4c14-99d5-b3943dc3c792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits'])[1]/preceding::th[1]</value>
      <webElementGuid>8641e49b-0c49-487b-9ee4-78e02dc74dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductions'])[1]/preceding::th[2]</value>
      <webElementGuid>c1838daa-865d-474d-8f37-e4db0dcbf12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Earnings']/parent::*</value>
      <webElementGuid>ff530863-93e1-4da0-ab28-3a84a9f96c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>b156584c-73bc-46a5-a923-d00da374915f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Earnings' or . = 'Earnings')]</value>
      <webElementGuid>11cbcfee-3a77-49ce-b037-ac4a9363cc3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
