<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_valid Input value 2_department.Custom_848525</name>
   <tag></tag>
   <elementGuidId>39e74965-13e2-45f9-aacc-bff67b8a479e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#department_CustomFields_1_CustomField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='department_CustomFields_1_CustomField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;valid Input value 2:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bc012ee-2ef5-4617-a9d5-4b8a4c285539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c22a8b2-88c4-4380-94bb-439efcf958bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department_CustomFields_1_CustomField</value>
      <webElementGuid>d722c69d-70f2-4c92-adbb-c418ea439909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>department.CustomFields[1].CustomField</value>
      <webElementGuid>6d3593ea-bcfc-46ac-b62b-d006c834b298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>01f5a052-77ba-48aa-b17a-e37d5845534e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text dirty custom-field-input</value>
      <webElementGuid>3e2ddd11-4509-4aa5-a514-f3b461811d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department_CustomFields_1_CustomField&quot;)</value>
      <webElementGuid>153b9128-940f-40cd-8bda-2e18772f5681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='department_CustomFields_1_CustomField']</value>
      <webElementGuid>1a2757a0-6885-4b88-b82b-e16e598493ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDepartmentDetailAdd']/div[4]/div/div[2]/input</value>
      <webElementGuid>c6623b3d-8cac-450d-99de-1608abff0aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>0df7c38b-20e7-484e-8adc-3bb12b85cd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'department_CustomFields_1_CustomField' and @name = 'department.CustomFields[1].CustomField']</value>
      <webElementGuid>99c81b77-98b7-4fb0-97a9-1d39eb711918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
