<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Submitted Date</name>
   <tag></tag>
   <elementGuidId>e3154f44-7399-4c68-9728-abafff5edafa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fw-select[@id='viewSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Submitted Date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>ab4f51b7-5d74-458c-be05-7f6d112ec9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewSelect</value>
      <webElementGuid>1d5891c6-f7f3-4b08-8525-9ed262302cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>656ca0af-0a1b-4332-ad1e-a4c60ef3e73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>Id</value>
      <webElementGuid>7bef1fca-ac54-4f74-9bee-355ba80189ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select view option</value>
      <webElementGuid>218b9398-7c92-43b7-a3ff-e6cfb7664a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>view</value>
      <webElementGuid>310e4983-7ab1-4ed7-8141-251901a325d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select filter-select ng-valid ng-untouched ng-pristine</value>
      <webElementGuid>b71d3f0b-1227-456f-86e0-c9f2c24c09ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b98edf51-0daa-4cd4-adce-0a3b53e868ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Submitted Date</value>
      <webElementGuid>48791400-d81b-4b47-9807-2dac2a774545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submitted Date</value>
      <webElementGuid>dddc0090-fa2c-4941-a1cc-7f67ede10dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewSelect&quot;)</value>
      <webElementGuid>4dda5b92-d02c-45b2-a38e-fd70493d3677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//fw-select[@id='viewSelect']</value>
      <webElementGuid>0358bfd1-20e3-4527-b584-48c2498296a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::fw-select[1]</value>
      <webElementGuid>ebe1b791-6d2e-4b4d-baac-04144144a80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Departments'])[1]/following::fw-select[1]</value>
      <webElementGuid>dd5f36f4-f923-435f-b1c1-a16247b39ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/preceding::fw-select[1]</value>
      <webElementGuid>a910cab3-4ea3-4f95-8f06-79a30ff6b0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-select</value>
      <webElementGuid>68517f6f-0507-401f-b925-31c0e3f1f140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'viewSelect' and @placeholder = 'Select view option' and @title = 'Submitted Date' and (text() = 'Submitted Date' or . = 'Submitted Date')]</value>
      <webElementGuid>01cca30e-2412-4dc3-b808-069eaf6047f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
