<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_UywwFc-RLmnJb</name>
   <tag></tag>
   <elementGuidId>32d55264-fc7d-40f6-af1d-5cce788d1470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.UywwFc-RLmnJb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' UywwFc-RLmnJb ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Join now&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29409fe7-8b43-4e97-a5fa-eb541e2bcc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>UywwFc-RLmnJb</value>
      <webElementGuid>f2d1fcbe-4aea-4df9-ae5b-1e094860ccbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e8d880e68b4773892be8fc8054246023</value>
      <webElementGuid>5eeedc49-19cb-44b2-90fe-affee65996bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' UywwFc-RLmnJb ')]</value>
      <webElementGuid>77d4e199-832a-4c8b-ae70-94f9cf58cb44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' UywwFc-RLmnJb ')]</value>
      <webElementGuid>14308cc7-80ea-4f49-908a-3fb70c296556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
