<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_SIL</name>
   <tag></tag>
   <elementGuidId>e3319216-7e3e-4f16-93c5-649f4ac21661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/div/fw-default-filter/ul/li[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.u-flex.ng-untouched.ng-pristine.ng-valid.ng-star-inserted > label.u-m-left--half</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SIL&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>433fdaf4-3f35-401f-b025-b490e7c39d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-m-left--half</value>
      <webElementGuid>16e2cd6d-e52d-4ad6-8e82-2dd596edd162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>HomeDepartmentName1</value>
      <webElementGuid>ee007f01-c7f5-4735-9eb7-abd14bf58307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIL</value>
      <webElementGuid>e42c8397-865a-4d7c-8852-5693fea324b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/div[@class=&quot;fw-filter-overlay u-flex--100 ng-star-inserted&quot;]/fw-default-filter[@class=&quot;u-flex u-flex--column ng-star-inserted&quot;]/ul[1]/li[@class=&quot;u-flex ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/label[@class=&quot;u-m-left--half&quot;]</value>
      <webElementGuid>0cae86c5-62ba-450d-b027-aee645341298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/div/fw-default-filter/ul/li[2]/label</value>
      <webElementGuid>8b43c71f-d33b-44f3-ad40-b75165e4863d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anemone House'])[1]/following::label[1]</value>
      <webElementGuid>62afcea6-1180-48cd-9440-83dc27c1c109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/following::label[2]</value>
      <webElementGuid>64d2a10e-161e-4ee1-8744-8726763c4416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear filter'])[1]/preceding::label[1]</value>
      <webElementGuid>74065628-0201-4ccc-a460-00a731bf2527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label</value>
      <webElementGuid>ddf0a71b-902f-4448-9ac9-476f6ab09ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'SIL' or . = 'SIL')]</value>
      <webElementGuid>cc2a1c10-8c4a-43e2-90e9-fe3fc811fe0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
