<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Home Department filter_list</name>
   <tag></tag>
   <elementGuidId>b6c12b4f-7835-4883-b40e-362a7e456b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='filter_list'])[3]/following::th[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.col--home-department</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;Home Department filter_list&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>91e2df00-9edd-4da9-903e-b60d0f4a14b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>a403543d-8fd9-403a-b040-505b78df8cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fwsortby</name>
      <type>Main</type>
      <value>HomeDepartmentName</value>
      <webElementGuid>2a719c47-94db-4bcd-b6d9-ad384d293793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fwfilterid</name>
      <type>Main</type>
      <value>HomeDepartmentName</value>
      <webElementGuid>bdcecedd-da85-45e8-bc70-795d6e2a337a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fwfilterpropertyname</name>
      <type>Main</type>
      <value>HomeDepartmentName</value>
      <webElementGuid>bdcb400f-1b02-490d-80d8-603f8152907d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col--home-department</value>
      <webElementGuid>4405c660-5de1-4f11-91ce-f9a0c81e5018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Home Department filter_list</value>
      <webElementGuid>5a28e2e8-dfc0-4d70-aa5c-6b15372fff21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;material-icons--loaded&quot;]/spa-app[1]/fw-framework-body[1]/fw-content[1]/main[1]/spa-time-off-admin-container[@class=&quot;routed-container ng-star-inserted&quot;]/spa-time-off-admin[@class=&quot;work-surface__content ng-star-inserted&quot;]/spa-request-admin-table[1]/table[@class=&quot;grid-lite&quot;]/thead[1]/tr[1]/th[@class=&quot;col--home-department&quot;]</value>
      <webElementGuid>bfcc5271-21fb-4a30-b4c3-8347c3a13ab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='filter_list'])[3]/following::th[1]</value>
      <webElementGuid>cb14649a-8a23-4fb4-a70c-2d82003bc07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home Department']/parent::*</value>
      <webElementGuid>44670293-9ba0-44cf-9072-a026d5afe1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]</value>
      <webElementGuid>64d80c18-098a-4581-a8b5-a13b97eea512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = ' Home Department filter_list' or . = ' Home Department filter_list')]</value>
      <webElementGuid>797df7ae-1ccb-43c7-8138-ae0fe91f9fc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
