<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Determined using a formula_notApplicable</name>
   <tag></tag>
   <elementGuidId>a340a665-03fa-4abd-9b55-cc52040938a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notApplicable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notApplicable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Not applicable&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a8e33f3-3bb4-43b2-9f9f-12fe7057257d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>39cabdbd-2414-4a2c-bcfe-a66b3f949695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notApplicable</value>
      <webElementGuid>a25a0a91-97e6-4238-bbb2-ca10ae2c5271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>PayRateCategoryCode</value>
      <webElementGuid>7fc9de6d-a32a-4822-a09c-d045bc9374fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-pristine ng-valid ng-touched</value>
      <webElementGuid>fa2f43ec-5cdc-4464-a7e7-d49dbd7e01b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notApplicable&quot;)</value>
      <webElementGuid>96f9ac14-6c39-46f7-98bc-814f7fa2b28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notApplicable']</value>
      <webElementGuid>f64b0c1f-9a68-402a-89a6-ff03e8c814ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>98b2e623-7ef0-47e5-a2fc-86ebf9208b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'notApplicable']</value>
      <webElementGuid>ee5d8fbb-4fc2-45be-8a30-1928ed254a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
