<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A fixed value or captured by the payr_667543</name>
   <tag></tag>
   <elementGuidId>b55edf77-9cd4-49cf-8897-cc5956959c56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isDefaultFormula</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isDefaultFormula']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Determined using a formula&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2ac38e3-0136-4d6b-ae34-4ceff201884f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1bbf17d7-01d0-4206-80eb-432ea687d144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isDefaultFormula</value>
      <webElementGuid>8658a605-7792-467a-8844-417d13d4f922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>IsDefaultFormula</value>
      <webElementGuid>1def39b8-364e-4cde-a059-346c8fb1a793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>582d28cc-09de-486d-89c6-664c11de9a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isDefaultFormula&quot;)</value>
      <webElementGuid>49aa24f5-f3e8-4dea-acaa-b9243926c87d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isDefaultFormula']</value>
      <webElementGuid>3171e6ac-4fb0-40e9-ab5e-bd9f2265400f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-organization-ebd-instruction-value-form/form/div[2]/input</value>
      <webElementGuid>f4246d99-bf28-4077-adcd-fb038a4f4f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'isDefaultFormula']</value>
      <webElementGuid>b2adc705-50c7-4ac1-b9e8-a827ffcc4ef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
