<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOME</name>
   <tag></tag>
   <elementGuidId>9d88ab23-3986-4608-809c-7180b30dd9b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='home-menu-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;HOME&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e51059a-ee71-46c8-9951-03c1e0b67e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item ng-tns-c2102510851-2 ng-star-inserted</value>
      <webElementGuid>cb6f50c0-f2a2-4acb-ac3d-e9abbcbee3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-menu-item</value>
      <webElementGuid>144f9877-fc6c-4f77-8c9f-be7401f6e2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.ibexpayroll.com:8443/edge5/Everest/Home/Index.mr</value>
      <webElementGuid>ce891305-14d4-473c-8e4c-a53f282e4c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> HOME </value>
      <webElementGuid>64ea2ce2-f46d-4647-b56d-55ab6a4315df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-menu-item&quot;)</value>
      <webElementGuid>059b4ad2-a715-4113-850f-25e6e8f9e201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='home-menu-item']</value>
      <webElementGuid>1088f346-d7cb-477e-b59b-8a52286c207f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HOME')]</value>
      <webElementGuid>3a86f907-7935-4cc3-94b0-a01fe11500e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info_outline'])[1]/following::a[1]</value>
      <webElementGuid>a8dc71c3-e4b2-4055-b76c-d2eecc601c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHEDULES'])[1]/preceding::a[1]</value>
      <webElementGuid>2e31470f-d741-4096-bcdf-b985be56694a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAILY APPROVAL'])[1]/preceding::a[2]</value>
      <webElementGuid>c46a7709-3e8f-4070-9cb6-2b28a7d138e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HOME']/parent::*</value>
      <webElementGuid>7ab1dbc0-eb82-4983-b945-6f3c1e63d343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.ibexpayroll.com:8443/edge5/Everest/Home/Index.mr')]</value>
      <webElementGuid>7f38565f-eb92-4197-8c8b-8444796ab8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-menu-item/a</value>
      <webElementGuid>b5df007b-bbc1-4909-a087-dd12337c05f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'home-menu-item' and @href = 'https://sit.ibexpayroll.com:8443/edge5/Everest/Home/Index.mr' and (text() = ' HOME ' or . = ' HOME ')]</value>
      <webElementGuid>bf4f4eb2-4d65-4df5-971b-53512f75e71f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
