<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_notApplicable</name>
   <tag></tag>
   <elementGuidId>3acab0a0-72e1-40bc-9544-3efa4d1af197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notApplicable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'notApplicable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Not applicable&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a3345c3-a664-4ead-ae83-6fbe51684b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1507cb46-62d6-4b4b-8c05-278591fe333e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notApplicable</value>
      <webElementGuid>896a1db5-7c09-494d-813e-c88f1b04f2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>PayRateCategoryCode</value>
      <webElementGuid>5bb19b1c-4e3b-4bd1-aec7-aecd842fc159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>fdf79ff7-c9ee-4d55-b2e9-5bbf7ced3c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>notApplicable</value>
      <webElementGuid>b6b1d122-7d84-43db-938f-1891ae73b02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4049676b09313c6fef5e56e62b3498a8</value>
      <webElementGuid>c1b0bde4-b693-4930-8607-42e598ecf1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'notApplicable']</value>
      <webElementGuid>415b6a5b-f2b0-4cbd-a6d9-802e4a46824e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'notApplicable']</value>
      <webElementGuid>b86ff813-82c0-43ed-a8bf-7d934229a379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'notApplicable' and (text() = 'notApplicable' or . = 'notApplicable')]</value>
      <webElementGuid>2dba84d4-15a3-4363-bc82-f1c6a02ebafe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
