<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valid Input Value 1_department.Custom_fcb433</name>
   <tag></tag>
   <elementGuidId>0b378ddb-a7c5-42e3-83bd-ec3e22e5c68d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#department_CustomFields_0_CustomField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='department_CustomFields_0_CustomField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Valid Input Value 1:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09782951-29ff-4954-923d-24b0aed801cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2fbc85e-665b-4fd8-8b7b-97411aaeeb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department_CustomFields_0_CustomField</value>
      <webElementGuid>0146a163-2a4a-40d3-ba20-b19009a1145c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>department.CustomFields[0].CustomField</value>
      <webElementGuid>c49e52f1-140d-4a74-b042-dbf3100e68f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>4ddee229-f858-4fe0-a4ab-b9eacbbeefdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text dirty custom-field-input</value>
      <webElementGuid>383481ec-f51b-4f0d-a752-6ada1c8ddab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department_CustomFields_0_CustomField&quot;)</value>
      <webElementGuid>c7dc75bd-01a6-4b39-a9af-06b9451ec06f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='department_CustomFields_0_CustomField']</value>
      <webElementGuid>af4da01c-d6fb-420b-8aa7-397c83ad3d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDepartmentDetailEdit']/div[3]/div/div[2]/input</value>
      <webElementGuid>92de42a4-5db1-46ff-97c4-be7437d9d572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>2f48aaed-2a42-48f8-8b2a-851219fa1f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'department_CustomFields_0_CustomField' and @name = 'department.CustomFields[0].CustomField']</value>
      <webElementGuid>f81d247a-c5da-4dd5-b5aa-66b84189657e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
