<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Valid Input Value 1</name>
   <tag></tag>
   <elementGuidId>35fb6505-9eed-4956-9f3b-c105ea7585d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmDepartmentDetailEdit']/div[3]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Valid Input Value 1:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1a03e99f-5a76-4630-83d7-6d9170e58e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>department_CustomFields_0_CustomField</value>
      <webElementGuid>e9e04f36-11e7-4501-a2c0-fd4be0ee6eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3d35beda-e704-4a59-864b-76cee3178a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valid Input Value 1:</value>
      <webElementGuid>265f5f1e-2637-42d3-8e4e-7605036b35a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDepartmentDetailEdit&quot;)/div[@class=&quot;form__row u-flex&quot;]/div[@class=&quot;form__row&quot;]/div[@class=&quot;form__label-group&quot;]/label[@class=&quot;label&quot;]</value>
      <webElementGuid>86497b79-7281-4942-bb88-6f3a394b1b73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDepartmentDetailEdit']/div[3]/div/div/label</value>
      <webElementGuid>a04dacf5-2e09-4207-b9f1-7235d5cfbf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department Name:'])[1]/following::label[1]</value>
      <webElementGuid>57eabb16-eaf3-4c1b-bb47-b82fad8c384b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Override GL Cost Center'])[1]/following::label[2]</value>
      <webElementGuid>da9ba4c9-b678-454f-856c-39b08ad376ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective Date:'])[1]/preceding::label[1]</value>
      <webElementGuid>df19582f-329a-465f-8136-6808c3f6a0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='valid Input value 2:'])[1]/preceding::label[2]</value>
      <webElementGuid>a9445587-f6c5-49ca-babb-827f209fd79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Valid Input Value 1:']/parent::*</value>
      <webElementGuid>b7099aef-3187-4fa8-9b16-a261d14f649f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>67f784cd-ad19-45f7-90f1-bcdcd14615cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Valid Input Value 1:' or . = 'Valid Input Value 1:')]</value>
      <webElementGuid>5a0102fb-5986-40cd-9e78-776ec1f527d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
