<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Days Requested</name>
   <tag></tag>
   <elementGuidId>7760e7ec-3944-4454-a73a-f7a77b6ac3f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fw-select[@id='viewSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Days Requested&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>d5b1b0bd-c94d-449c-b717-b0384ce1e4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewSelect</value>
      <webElementGuid>674de87b-0963-4f5d-8dbb-94632de3c631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>d3bf9903-5719-42bf-9e98-4be10c3ccae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>Id</value>
      <webElementGuid>808aafb0-875e-4454-aacf-00831cbe2c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select view option</value>
      <webElementGuid>edba0587-2a25-4499-9abc-506e3e6aa90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>view</value>
      <webElementGuid>61aa9b46-3038-4325-9992-8673411d5609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select filter-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7fb5a6fc-48f0-4490-bd01-7923cef85236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3f98d68-b04c-40a3-8b06-0b013eb1089b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Days Requested</value>
      <webElementGuid>3ce35151-9669-4bba-a10e-a269330165bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Days Requested</value>
      <webElementGuid>892ca59e-2863-4db4-adeb-68bd443c0bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewSelect&quot;)</value>
      <webElementGuid>cbe1d8a0-cea4-4a91-b9c6-981721fd2cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//fw-select[@id='viewSelect']</value>
      <webElementGuid>fb017cec-fc98-44ca-9196-750df9f5a17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::fw-select[1]</value>
      <webElementGuid>c979144a-41b4-4083-8da4-193be881e755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Departments'])[1]/following::fw-select[1]</value>
      <webElementGuid>1a1b7fbe-0c54-43fc-881c-1b89338fb607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/preceding::fw-select[1]</value>
      <webElementGuid>d93dde71-308b-42b6-920f-441bdf827d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-select</value>
      <webElementGuid>5ab3921b-452e-4be8-8e09-22f128ab673a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'viewSelect' and @placeholder = 'Select view option' and @title = 'Days Requested' and (text() = 'Days Requested' or . = 'Days Requested')]</value>
      <webElementGuid>ea49af3b-87d3-4385-b12b-7f283a12e6ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
