<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anns Test Org</name>
   <tag></tag>
   <elementGuidId>37fd538e-8ff1-415f-999f-39985a4a2505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ann's Test Org&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>39f535c6-b7df-4ff1-b081-fa4a21158864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CloseDialog(0);</value>
      <webElementGuid>6b0bcbb0-1d97-4de7-8e90-0aad127a4ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edge5/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6</value>
      <webElementGuid>bd01a4ff-0320-4b7b-9047-e49fca73dc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ann's Test Org</value>
      <webElementGuid>3768abf0-5703-4fe8-9d03-001101cc179c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridOrganizationDialogResults&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[1]</value>
      <webElementGuid>f07f04cf-d33d-4de5-a316-3e179974556d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='CloseDialog(0);'])[8]</value>
      <webElementGuid>986ec992-490f-4bb4-9a7b-fb05664a7bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridOrganizationDialogResults']/tbody/tr[4]/td[2]/a</value>
      <webElementGuid>a676ff81-1dbe-46cc-8069-6ee39e02b485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP7'])[1]/following::a[1]</value>
      <webElementGuid>78363526-4ee1-48c7-9025-70581fa8d6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ann BC Org'])[1]/following::a[2]</value>
      <webElementGuid>93f2cb19-6642-42b0-b9ab-dfdf371a50fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP-2'])[1]/preceding::a[1]</value>
      <webElementGuid>653a3394-bf98-45df-891d-3ad53c172b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/edge5/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6')])[2]</value>
      <webElementGuid>28cd1b94-9109-4293-886c-3ad30a248522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a</value>
      <webElementGuid>e324f140-0997-4191-98e3-0a7a55822a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edge5/everest/OrganizationContext/ChangeContext.mr?OrganizationId=d97d0e63-c0f3-448b-929e-f006bf22ccc6' and (text() = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;) or . = concat(&quot;Ann&quot; , &quot;'&quot; , &quot;s Test Org&quot;))]</value>
      <webElementGuid>a860ebd4-6ea2-4099-82c0-a750dc0371f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
