<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Schedules</name>
   <tag></tag>
   <elementGuidId>cc3873cf-74e9-48fe-b08d-75368c3de5e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-navigation-list > li.menuItem > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js-navigation-list']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Schedules&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f237c6a-213b-4f43-9ed5-b3ab0135edbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.ibexpayroll.com:8443/main/everestspa/schedules</value>
      <webElementGuid>be078f9a-5fdf-4dce-b1bc-98a56dad3492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Schedules</value>
      <webElementGuid>29edc764-96c9-42b5-8696-3a436065555b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-navigation-list&quot;)/li[@class=&quot;menuItem&quot;]/a[1]</value>
      <webElementGuid>3c7a9b78-d71e-4217-9d91-208a3dd684d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-navigation-list']/li[2]/a</value>
      <webElementGuid>9e64196a-5b22-4302-9ff6-8a1d55dde4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Schedules')]</value>
      <webElementGuid>5f4e0e3f-1d63-4f65-8c7c-d4bb51c931f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>45e32d33-c5d8-4d84-9aef-03bc348b165f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info_outline'])[2]/following::a[2]</value>
      <webElementGuid>b2128d4b-a9da-4745-bd90-e9a6a953f2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Approval'])[1]/preceding::a[1]</value>
      <webElementGuid>8bde56d8-299a-4a6b-9586-3abb4a1b5a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll'])[1]/preceding::a[2]</value>
      <webElementGuid>edebb885-e085-4434-b0ea-2d6a18d096e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Schedules']/parent::*</value>
      <webElementGuid>e8dae5c3-f853-4b07-a3b0-d074a2aae90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.ibexpayroll.com:8443/main/everestspa/schedules')]</value>
      <webElementGuid>79332488-9f27-4ddd-b7a6-2a5b10caa6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>3dcb0612-fa21-435e-9d5c-1c5b41e688cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.ibexpayroll.com:8443/main/everestspa/schedules' and (text() = ' Schedules' or . = ' Schedules')]</value>
      <webElementGuid>fb537966-4cdd-4dec-bca4-9141818803dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
