<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Department Field 1_field01Value</name>
   <tag></tag>
   <elementGuidId>12166f51-4d52-4908-8c2e-738ed3440eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_field01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_field01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txt_field01</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b6a7f7b-eab0-4a63-84a7-e3822a3353e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a27e5369-c92b-4a59-a66a-ff29c167ef71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_field01</value>
      <webElementGuid>ee35d094-64d9-4588-a24c-e19ca787af29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field01Value</value>
      <webElementGuid>1489b2e6-9e1e-4e3c-919b-cb7f2f944fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>fc690539-0e42-46f0-90e2-8141dc60ee8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_field01&quot;)</value>
      <webElementGuid>00885dfe-dd02-40cd-b527-d02d43eb8530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_field01']</value>
      <webElementGuid>050729bb-aae6-47b2-9c92-6d5f9098e5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>fc801a6a-7fdf-44ba-b13c-545dfcc490cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_field01' and @name = 'field01Value']</value>
      <webElementGuid>9f08d1c2-82d5-4e7f-be05-ce3133ad67f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
