<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_changePassword</name>
   <tag></tag>
   <elementGuidId>e0bc585e-ba64-436d-b175-59fb9bcebece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#changePassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'changePassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;lock Change Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>605b397f-8f05-4334-a449-e47c60592852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>46705def-7ba2-41d2-89cb-4d1e2488c61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changePassword</value>
      <webElementGuid>9521fa9d-f06c-45df-a6c6-c52a95486963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-m-right</value>
      <webElementGuid>a27f79d7-d2c7-487c-8392-35c8ed9d94d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>changePassword</value>
      <webElementGuid>8124f9c0-04fa-4242-95da-034b3857f1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>lock
Change Password</value>
      <webElementGuid>aea7c152-ed20-459f-b1b0-1041ff12b2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-aa683323999c082ecf142d2bc954d7a5</value>
      <webElementGuid>728ccbce-b632-4add-86a4-a63de78545b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'changePassword']</value>
      <webElementGuid>5a09aabc-9658-4b61-8123-c0dc51eb6d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'changePassword']</value>
      <webElementGuid>6be39dcc-0a3c-4d20-a016-8708e48bc598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'changePassword' and (text() = 'changePassword' or . = 'changePassword')]</value>
      <webElementGuid>9b6ef31d-da34-4d5c-ab88-85eb884dc388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
