<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Department Field 1_field01Value</name>
   <tag></tag>
   <elementGuidId>aab37196-54a8-4d80-bb74-aae23e27c029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_field01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_field01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txt_field01</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c5c702f-e2d0-4fe2-9431-73c682656053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a0049cb-8071-4c30-9855-35b7ca2b3223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_field01</value>
      <webElementGuid>6dcd2c70-d60b-4c8d-b481-617b6b2ca62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field01Value</value>
      <webElementGuid>aa2cf09d-264c-436f-b749-1d8ffe90d47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5a7b1f5b-fb3b-4048-99c4-004736369b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_field01&quot;)</value>
      <webElementGuid>ab791494-3cf3-4e39-825a-8662f318a380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_field01']</value>
      <webElementGuid>495af8d2-6d94-41fe-bb48-0f5ee0c49026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cc8676bc-643c-4294-8be3-d40461512096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_field01' and @name = 'field01Value']</value>
      <webElementGuid>61992b4d-db21-4dfa-a4cd-a1225e08938e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
