<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nameFrench</name>
   <tag></tag>
   <elementGuidId>72ab990f-2061-47c2-ab58-25b1fb70aeca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameFrench</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nameFrench']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nameFrench</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf8cc353-f41c-4f0d-85cf-998972609945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77a6745f-0fa0-4ca9-8b78-1a7e7860927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>69020b4b-dce5-49b4-9408-808678502020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>NameFrench</value>
      <webElementGuid>6e6eed31-a664-4464-95a1-604e74a82f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f2fae5c5-d50a-46bf-af9d-989169815bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>5ee43db2-3430-4a04-b388-29e94c010d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b2d50dbd89a59c761b01381853be16aa</value>
      <webElementGuid>a8cd4e66-4f44-45c7-98a8-05fc46e93f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>02d815f1-8977-463b-88e3-131f14cc2202</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>f4fc61d2-650c-4f04-8fd8-63f02ff9f3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameFrench' and (text() = 'nameFrench' or . = 'nameFrench')]</value>
      <webElementGuid>2b40be9d-0b52-4bf7-a676-7084a23bff55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
