<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applies to</name>
   <tag></tag>
   <elementGuidId>b1a5d7cd-0197-4541-944d-14f6c07b7413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isAppliedToAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'isAppliedToAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Applies to:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8ca1b3d-8165-455b-8aee-ff9d86f81a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eed1f11a-d781-4ef0-8c8e-771a7ce37d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isAppliedToAll</value>
      <webElementGuid>b6219620-211a-4e60-98af-ac626136c2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>IsAppliedToAll</value>
      <webElementGuid>e4df3f53-6583-42d5-9af5-ff90c9026fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-checkbox ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>627b5177-395f-4b0a-9109-1a41358516fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Applies to</value>
      <webElementGuid>51b039fc-d757-4a0a-b423-65698c7bf1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e2adbcc22a1f1dadda78e6acc2984fe</value>
      <webElementGuid>6a1e226a-eeda-4581-9e64-b6aea06a84f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'isAppliedToAll']</value>
      <webElementGuid>4a9b2fa7-fca4-4e04-bc3f-f0d4d28688dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'isAppliedToAll']</value>
      <webElementGuid>4707940e-3cf3-47b1-867f-d119975c54ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isAppliedToAll' and (text() = 'Applies to' or . = 'Applies to')]</value>
      <webElementGuid>ec423ddf-b47a-4dcd-b2a1-39625e45072c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
