<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_0.00</name>
   <tag></tag>
   <elementGuidId>e59e804d-778c-4617-9863-db3938bf67a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total-hours > spa-hour-cell > a[title=&quot;0.00&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='total-hours']/spa-hour-cell/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#total-hours >> internal:text=&quot;0.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8831206b-1c92-4e58-8a99-a84d696e588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>efcf4b34-e6f7-4864-9512-fb8afd73c124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>7bab4b1b-ee98-4304-bc1f-604060f1c184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total-hours&quot;)/spa-hour-cell[1]/a[1]</value>
      <webElementGuid>51232e7e-ec59-4387-a8d8-7b1808ddef3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='total-hours']/spa-hour-cell/a</value>
      <webElementGuid>6d2e2713-5593-45d2-a246-6d399c00c071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'0.00')])[3]</value>
      <webElementGuid>6121a328-5e86-41d1-8406-fb57d6696530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[3]</value>
      <webElementGuid>c6a6c25e-6a71-48b2-a44e-c715c4bc65fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/following::a[3]</value>
      <webElementGuid>2f3948ca-6d4d-4f0c-8a93-91ce96a0c195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/preceding::a[1]</value>
      <webElementGuid>77f9869a-a828-4f68-b0ef-fc1670a644a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/preceding::a[1]</value>
      <webElementGuid>302933cf-ec2f-4815-a247-da02e9fa26e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/spa-hour-cell/a</value>
      <webElementGuid>bfaad2d0-c67f-4e9d-8c53-ff69183a1b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = '0.00' and (text() = '0.00' or . = '0.00')]</value>
      <webElementGuid>4ac40984-46da-45c5-90c8-caaa749ec894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
