<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1,019.15</name>
   <tag></tag>
   <elementGuidId>d01e7529-6f3b-4413-a4a0-fa6e033f1dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total-hours > spa-hour-cell > a[title=&quot;1,019.15&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='total-hours']/spa-hour-cell/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#total-hours >> internal:text=&quot;1,019.15&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b626415a-040d-4295-b4db-2bf9de1d444e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1,019.15</value>
      <webElementGuid>906a6a74-fafa-45ed-8285-65240d318f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1,019.15</value>
      <webElementGuid>0df8b917-d277-46d2-9ac2-340f980ff70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total-hours&quot;)/spa-hour-cell[1]/a[1]</value>
      <webElementGuid>d0ec6e64-34ca-4d25-b98f-fa2d20ac2f63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='total-hours']/spa-hour-cell/a</value>
      <webElementGuid>21cc51a1-24e8-4a0e-81ad-12b493e16e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'1,019.15')])[2]</value>
      <webElementGuid>804a69c5-d84c-431e-b420-fcdbe50a5da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[3]</value>
      <webElementGuid>1734f8c2-4d05-4388-9b48-4e2b1883a577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/following::a[3]</value>
      <webElementGuid>1af99574-3a43-4cb8-9822-bd3773e9eb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand row'])[1]/preceding::a[1]</value>
      <webElementGuid>89dc4d3a-4a46-418f-a3a6-e69fe536f8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/preceding::a[1]</value>
      <webElementGuid>4e41a4df-149b-4e43-8164-cba546845f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/spa-hour-cell/a</value>
      <webElementGuid>d1451b6c-4e84-4c4a-98aa-ee6867cb6ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = '1,019.15' and (text() = '1,019.15' or . = '1,019.15')]</value>
      <webElementGuid>cb7fd794-246f-4f4b-ad9d-51054bcb2ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
