<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-tabs_Summaryfiber_manual_recordFiltersfi_f8a64b</name>
   <tag></tag>
   <elementGuidId>552db20f-4c1b-4e1b-899e-b5c7c1d4135f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>fw-tabs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='chevron_left'])[1]/following::fw-tabs[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>fw-tabs</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-tabs</value>
      <webElementGuid>1e6f5046-c463-4ac6-85c0-e7dfc5d69af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summaryfiber_manual_recordFiltersfiber_manual_recordDisplay Optionsfiber_manual_recordSummary of Hours List by: EmployeeDepartmentDatePayCodeMatch Status then summarize by: EmployeeDatePayCodeMatch StatusUnapprovedApprovedTotal1,248.000.001,248.00Expand rowexpand_more Bravo House 632.000.00632.00Expand rowexpand_more Charlie House 616.000.00616.00FiltersClear All Employee no filter Department no filter PayCode no filter Match Status no filter Status  Unapproved  Date Range 10 Mar, 2024 - 23 Mar, 2024 Lock Status no filter Worked Status no filterDisplay Options Name Display First Name first (Emma Price)Last name first (Price, Emma)Apply</value>
      <webElementGuid>5aa2c141-dc5e-4494-97fa-decb592cdbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;material-icons--loaded&quot;]/spa-app[1]/fw-framework-body[1]/fw-content[1]/main[1]/spa-daily-approvals[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;work-surface&quot;]/spa-daily-approval-details[@class=&quot;enabled active ng-star-inserted&quot;]/div[@class=&quot;detail-panel__content&quot;]/fw-tabs[1]</value>
      <webElementGuid>73ec3d96-1c91-4b66-9a87-7713cce2bbf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chevron_left'])[1]/following::fw-tabs[1]</value>
      <webElementGuid>33ac8754-c1c8-4d2b-9c36-d8a79d24e69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATTENDANCE'])[1]/following::fw-tabs[1]</value>
      <webElementGuid>c9920e8d-c9d4-4ff7-b939-fc8c5550b611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-tabs</value>
      <webElementGuid>823a6efb-23c0-4220-aeec-c6cd004d88d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-tabs[(text() = 'Summaryfiber_manual_recordFiltersfiber_manual_recordDisplay Optionsfiber_manual_recordSummary of Hours List by: EmployeeDepartmentDatePayCodeMatch Status then summarize by: EmployeeDatePayCodeMatch StatusUnapprovedApprovedTotal1,248.000.001,248.00Expand rowexpand_more Bravo House 632.000.00632.00Expand rowexpand_more Charlie House 616.000.00616.00FiltersClear All Employee no filter Department no filter PayCode no filter Match Status no filter Status  Unapproved  Date Range 10 Mar, 2024 - 23 Mar, 2024 Lock Status no filter Worked Status no filterDisplay Options Name Display First Name first (Emma Price)Last name first (Price, Emma)Apply' or . = 'Summaryfiber_manual_recordFiltersfiber_manual_recordDisplay Optionsfiber_manual_recordSummary of Hours List by: EmployeeDepartmentDatePayCodeMatch Status then summarize by: EmployeeDatePayCodeMatch StatusUnapprovedApprovedTotal1,248.000.001,248.00Expand rowexpand_more Bravo House 632.000.00632.00Expand rowexpand_more Charlie House 616.000.00616.00FiltersClear All Employee no filter Department no filter PayCode no filter Match Status no filter Status  Unapproved  Date Range 10 Mar, 2024 - 23 Mar, 2024 Lock Status no filter Worked Status no filterDisplay Options Name Display First Name first (Emma Price)Last name first (Price, Emma)Apply')]</value>
      <webElementGuid>e2e73527-7fc0-4452-9e51-b00b43c63a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
