<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-tabs_Summaryfiber_manual_recordFiltersfi_f8a64b</name>
   <tag></tag>
   <elementGuidId>552db20f-4c1b-4e1b-899e-b5c7c1d4135f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>fw-tabs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='chevron_left'])[1]/following::fw-tabs[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>fw-tabs</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-tabs</value>
      <webElementGuid>61667567-15d0-4029-abf3-dc8902766c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summaryfiber_manual_recordFiltersfiber_manual_recordDisplay Optionsfiber_manual_recordSummary of Hours List by: EmployeeDepartmentDatePayCodeMatch Status then summarize by: EmployeeDatePayCodeMatch StatusUnapprovedApprovedTotal1,248.000.001,248.00Expand rowexpand_more Bravo House 632.000.00632.00Expand rowexpand_more Charlie House 616.000.00616.00FiltersClear All Employee no filter Department no filter PayCode no filter Match Status no filter Status  Unapproved  Date Range 10 Mar, 2024 - 23 Mar, 2024 Lock Status no filter Worked Status no filterDisplay Options Name Display First Name first (Emma Price)Last name first (Price, Emma)Apply</value>
      <webElementGuid>bd7cc3b2-109a-4942-8f28-18ac98a5d736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;material-icons--loaded&quot;]/spa-app[1]/fw-framework-body[1]/fw-content[1]/main[1]/spa-daily-approvals[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;work-surface&quot;]/spa-daily-approval-details[@class=&quot;enabled active ng-star-inserted&quot;]/div[@class=&quot;detail-panel__content&quot;]/fw-tabs[1]</value>
      <webElementGuid>30658846-0f3b-4fa6-b4f7-4ab8930aa18d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chevron_left'])[1]/following::fw-tabs[1]</value>
      <webElementGuid>ff4a363c-5010-41d1-89ac-2b53d6e4ba74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATTENDANCE'])[1]/following::fw-tabs[1]</value>
      <webElementGuid>3e84486b-f2db-4af4-818c-1b6f833a156c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-tabs</value>
      <webElementGuid>38f70e11-6b1a-463c-8bb3-978ed5812e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-tabs[(text() = 'Summaryfiber_manual_recordFiltersfiber_manual_recordDisplay Optionsfiber_manual_recordSummary of Hours List by: EmployeeDepartmentDatePayCodeMatch Status then summarize by: EmployeeDatePayCodeMatch StatusUnapprovedApprovedTotal1,248.000.001,248.00Expand rowexpand_more Bravo House 632.000.00632.00Expand rowexpand_more Charlie House 616.000.00616.00FiltersClear All Employee no filter Department no filter PayCode no filter Match Status no filter Status  Unapproved  Date Range 10 Mar, 2024 - 23 Mar, 2024 Lock Status no filter Worked Status no filterDisplay Options Name Display First Name first (Emma Price)Last name first (Price, Emma)Apply' or . = 'Summaryfiber_manual_recordFiltersfiber_manual_recordDisplay Optionsfiber_manual_recordSummary of Hours List by: EmployeeDepartmentDatePayCodeMatch Status then summarize by: EmployeeDatePayCodeMatch StatusUnapprovedApprovedTotal1,248.000.001,248.00Expand rowexpand_more Bravo House 632.000.00632.00Expand rowexpand_more Charlie House 616.000.00616.00FiltersClear All Employee no filter Department no filter PayCode no filter Match Status no filter Status  Unapproved  Date Range 10 Mar, 2024 - 23 Mar, 2024 Lock Status no filter Worked Status no filterDisplay Options Name Display First Name first (Emma Price)Last name first (Price, Emma)Apply')]</value>
      <webElementGuid>5fb79cbc-445e-4935-ad81-5b74d86da85b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
