<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_today</name>
   <tag></tag>
   <elementGuidId>21351331-6778-4fc7-9d89-fe1c942bbc47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-group-addon > i.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='q-datepicker_1']/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#q-datepicker_1 >> internal:text=&quot;today&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>db99fd53-c29c-4377-b407-006b02ea4fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>1739ffe5-eebc-433b-8596-f8d8905d8927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>today</value>
      <webElementGuid>c87aac9f-9fca-4739-a217-c46d0190e698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;q-datepicker_1&quot;)/div[@class=&quot;input-group-addon&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>6d1aaf97-8789-43ad-b3c5-61f97f620d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='q-datepicker_1']/div/i</value>
      <webElementGuid>82c39d28-43bd-43ba-9132-6482db74ebb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='navigate_before'])[1]/following::i[1]</value>
      <webElementGuid>f8ef45ac-719f-4517-92aa-6d2f85c66600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Approval'])[1]/following::i[2]</value>
      <webElementGuid>f3a686fd-9e1a-4b5d-9a0d-15212c162f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='navigate_next'])[1]/preceding::i[1]</value>
      <webElementGuid>46884884-6cae-4fdc-b159-29ae68a14704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Calc'])[1]/preceding::i[2]</value>
      <webElementGuid>df650c54-7ef7-422a-8e39-29174ee506a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='today']/parent::*</value>
      <webElementGuid>51fd20e8-cf82-4a58-988b-6e6c6ef815fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//datetime/div/div/div/i</value>
      <webElementGuid>a2b47cee-ce96-472b-854a-da75b109f3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'today' or . = 'today')]</value>
      <webElementGuid>4f83d984-c1c9-4e05-b32c-6285490ae30e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
