<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Toggle Selection of All Rows_selectAll</name>
   <tag></tag>
   <elementGuidId>303fc434-ad91-4991-ae32-80f6a002177f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Toggle Selection of All Rows&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ccf510f-2f51-4474-a1ad-e8af19ba24cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dc8848d5-b9d2-445d-9dc1-2f993cdbb6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectAll</value>
      <webElementGuid>b0c0d824-8ae5-4ce7-897c-fd536381b405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectAll&quot;)</value>
      <webElementGuid>34c56bfb-7f2b-4870-9425-6a6f55d524c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectAll']</value>
      <webElementGuid>ea78e295-fbc9-4db0-9f96-ce444e8790f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-daily-approval-table/div/div/div[2]/input</value>
      <webElementGuid>6eaf449a-5299-4666-81fc-a8ebc80ee30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectAll']</value>
      <webElementGuid>cf7be752-f86e-4065-ba0f-e1b8f5600e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
