<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Biweekly-26</name>
   <tag></tag>
   <elementGuidId>c5583822-60e9-40f4-ba86-3fcb9762d72c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.odd:nth-child(8) td:nth-child(2) a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 8)]//*[(name() = 'td') and (position() = 2)]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Biweekly-26&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8f616aa-f7b5-43d5-be4f-3a2987b09eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CloseDialog(0);</value>
      <webElementGuid>176a58db-8912-4b9e-a799-3f768c027399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edge8/everest/OrganizationContext/ChangeContext.mr?OrganizationId=93f88c00-f4ee-4710-ac5b-476efd79fade</value>
      <webElementGuid>404f38d1-8fec-44c9-a755-894d65ebdef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biweekly-26</value>
      <webElementGuid>c725543d-d9c2-43cb-a8fb-119b3977afc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Biweekly-26</value>
      <webElementGuid>74a68eec-ed86-4d55-8385-4b5ff6d9c39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a57a99ec1969ad247b466396a8ba75f0</value>
      <webElementGuid>cedf46b7-d587-4140-a4ee-f223da042425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 8)]//*[(name() = 'td') and (position() = 2)]//a</value>
      <webElementGuid>7ee39512-084f-4e18-b476-8b15fdf1be2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' odd ') and (position() = 8)]//*[(name() = 'td') and (position() = 2)]//a</value>
      <webElementGuid>0790cea0-042c-41e7-831a-b2d4f9d3305f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edge8/everest/OrganizationContext/ChangeContext.mr?OrganizationId=93f88c00-f4ee-4710-ac5b-476efd79fade' and (text() = 'Biweekly-26' or . = 'Biweekly-26')]</value>
      <webElementGuid>88043327-e461-49ae-8792-b661d94e8aaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
