<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Department Field 1_field01Value</name>
   <tag></tag>
   <elementGuidId>bb3f912e-e7e3-41cc-8601-9c86878b779e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_field01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_field01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txt_field01</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12dea9ac-b21d-4d4b-ba62-9dba10232212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e86663b-fe48-4752-8cb2-29f11403b770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_field01</value>
      <webElementGuid>c0b2fa18-9f2e-4e54-924d-bd5d3d588bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field01Value</value>
      <webElementGuid>b4d84d51-bd56-4a2a-92b0-9fbe82c981fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2fe01b8c-5fbb-4153-9f07-67a6ef185f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_field01&quot;)</value>
      <webElementGuid>15050c06-ded5-4ba8-b30a-0b1e2edde728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_field01']</value>
      <webElementGuid>12293868-e616-4290-bd4a-8931351f849c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>04235a7c-cf14-43da-915a-0058e4aca249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_field01' and @name = 'field01Value']</value>
      <webElementGuid>3b04c869-cf87-4aa1-b565-c02255fc1281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
