<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_WeekPay PeriodMonth</name>
   <tag></tag>
   <elementGuidId>0bdea297-b980-4fa6-9acd-d1596a981d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='spanSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spanSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;View&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>133a2f4b-5d8b-433d-9ef5-32ad64b48981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanSelect</value>
      <webElementGuid>8c5b650f-312f-4717-b399-18d1c000cb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-select ng-tns-c532717066-5 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>63d29b1a-3ab9-49be-ab87-b0d328ddc31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WeekPay PeriodMonth</value>
      <webElementGuid>d08686b3-c74f-483a-9065-6609cec301d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanSelect&quot;)</value>
      <webElementGuid>86a7cf68-6b62-4612-9c77-9b8b1a9e5c6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='spanSelect']</value>
      <webElementGuid>2c6aefbc-b063-43d0-b849-3404505e9e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::select[1]</value>
      <webElementGuid>7adc5631-e375-458b-b5fc-58f370339021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='navigate_next'])[1]/following::select[1]</value>
      <webElementGuid>6379e576-26e0-4355-ac75-edb079b7ee7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[1]/preceding::select[1]</value>
      <webElementGuid>c6849a74-b80c-4471-aaa8-a63531f807c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/preceding::select[2]</value>
      <webElementGuid>bb257a45-1294-4f3b-9aad-17613ea55cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>031f7f62-bfdb-45c4-b869-c9879dda34eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'spanSelect' and (text() = 'WeekPay PeriodMonth' or . = 'WeekPay PeriodMonth')]</value>
      <webElementGuid>2b9647da-f798-4e05-a8e4-2039f279f620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
