<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Instruction Type</name>
   <tag></tag>
   <elementGuidId>d951f9eb-4563-4d15-ba32-dcd204623fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#earningType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'earningType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Benefit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>4b0b6ca4-921e-44c8-804a-cb41492769cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>ca72e027-8610-4c9e-8009-edc8bc34a33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>b3e255a2-d7d9-4b34-b567-4686345fee85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>EarningTypeObjId</value>
      <webElementGuid>234a6600-2f2f-44af-a3d2-4e3c49f039c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>5a8a88fb-8dfa-4cd8-93fb-1493dcf30a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>earningType</value>
      <webElementGuid>ce2c4493-aa9b-435f-99f7-3eb861992f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>73373c2f-ede7-4592-bae7-a31c3a33820d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48bad7aa-3c3e-47a7-8251-06952948389d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Benefit</value>
      <webElementGuid>ee465f72-0c0a-4b2b-8bf1-704cc95a829c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instruction Type</value>
      <webElementGuid>d7c36b4e-ef00-4bc5-983c-f99065fa66ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Benefit</value>
      <webElementGuid>137f8ebd-7d7d-4afa-bbd7-4c7f3854cc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c1cc50b302543504a3e1a359e45e25cb</value>
      <webElementGuid>c67d2aed-0a9c-480d-9b25-08eb55bccbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'earningType']</value>
      <webElementGuid>035e0589-fb5c-4a18-98b3-13edccc78ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'earningType']</value>
      <webElementGuid>e063f8af-676f-4c27-96f1-a0b088b32941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'earningType' and @title = 'Benefit' and (text() = 'Instruction Type' or . = 'Instruction Type')]</value>
      <webElementGuid>422f1e1f-f5d6-4f75-9318-849eb6425d81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
