<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Input value type</name>
   <tag></tag>
   <elementGuidId>c0fe6072-5847-45e9-a464-827fd0cdd004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputTypeObjId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'inputTypeObjId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Hours&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>6761b7b1-67b4-4dee-9ed6-5a62f4a46383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputTypeObjId</value>
      <webElementGuid>6db63872-49d9-44ca-b67d-6c7129c6f676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>c83314b9-68f0-4a3b-b7fd-991577811303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>5b5b3374-703b-4622-9283-cd1327aabcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>InputTypeObjId</value>
      <webElementGuid>12f57f25-7a30-4bdf-a3ec-6346b3bd69a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>16b7424a-6e3d-4bc4-9296-8b33d3e9d82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7dffae34-9fdc-49b4-8197-6397441197f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dc94363a-26c7-4eef-b85b-dff0020f4bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>0607eec5-b5a9-4e39-ab27-eaef5f541cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Input value type</value>
      <webElementGuid>8ce59763-13d6-47ff-b65e-ff6da8dad147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>a831aaaf-be05-4562-a5e3-7d74e0133323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fec515dfd93c0de8f5fcf167069b9c87</value>
      <webElementGuid>c4c78110-d8ac-49b3-846f-ef1d767a05da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>e9ad7b26-97fd-40f7-8079-9ca55d473c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>ca5b9ea4-e9d1-4d62-9109-f5b169229cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'inputTypeObjId' and @title = 'Hours' and (text() = 'Input value type' or . = 'Input value type')]</value>
      <webElementGuid>f7e38919-891a-4962-b3e7-c2783c515719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
