<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nameFrench</name>
   <tag></tag>
   <elementGuidId>2f1ccbf4-514b-402d-9e1e-ebd9a471829a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nameFrench</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nameFrench']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nameFrench</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff5422ae-c3f4-4749-a38b-1d027ae883f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2a6d9f8-22d5-4eec-9071-242aa74bf6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>e63929a3-3c7f-42d9-9986-d34b1935fd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>NameFrench</value>
      <webElementGuid>284543c3-a9ed-4e18-a2cf-e45119ef63d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text input-text--large ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>aee323c7-e2c0-45a7-a9b2-481f4506a2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nameFrench</value>
      <webElementGuid>324fa879-b64e-4327-a803-9d80b4dba1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b2d50dbd89a59c761b01381853be16aa</value>
      <webElementGuid>28c09e76-a431-4725-ba32-e8a2be397025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>311dd721-dbee-4367-ae38-585699ec5b81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nameFrench']</value>
      <webElementGuid>44b7874d-8ec4-4c75-933d-8342e869eb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameFrench' and (text() = 'nameFrench' or . = 'nameFrench')]</value>
      <webElementGuid>3caad042-9401-4975-b116-45f8d15f7d93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
