<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Formula Code</name>
   <tag></tag>
   <elementGuidId>e60f04a2-91e6-451e-a2a4-af693f376b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formulaCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formulaCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Formula Code:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>082ad0cb-cf07-44bb-af51-f49931939721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98b93955-3f54-4936-9114-d1f88485bfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulaCode</value>
      <webElementGuid>d573a4fc-d998-4af5-a05b-8c4caa353b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>FormulaCode</value>
      <webElementGuid>c0f8b82f-329b-4e95-9306-8374c60870a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8a1927e5-8ef2-4a9f-8eda-4ecb01026835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formula Code</value>
      <webElementGuid>a4ed9a54-c722-452b-9017-b9061815564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d58b1de1ad9ef82ded1b3f1c88b97baf</value>
      <webElementGuid>ead255c9-3b95-48a1-8010-c399f58a491d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formulaCode']</value>
      <webElementGuid>3a72ffa2-0f78-463d-a95d-b7ceb31d4838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formulaCode']</value>
      <webElementGuid>cdc510eb-e2ff-4c10-a660-be23aabf5675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formulaCode' and (text() = 'Formula Code' or . = 'Formula Code')]</value>
      <webElementGuid>fe4b88d1-1919-4609-93c3-1ede10ae5ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
