<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_swap_horiz Switch SetupSimpleDialog(orgCo_55ee7d</name>
   <tag></tag>
   <elementGuidId>0981cd91-eeaa-4c59-9219-7487509fea18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contextSwitch--navheader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='contextSwitch--navheader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;swap_horiz Switch&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad7e5432-d215-4e86-8571-4c083fc3d2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contextSwitch--navheader</value>
      <webElementGuid>8693d8fe-03be-4696-9c48-2215c783375a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>aad2d226-debe-4c94-9cde-8e291984805b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navheader__icon-link-stack u-m-horizontal</value>
      <webElementGuid>6db47274-69d7-40a4-9181-ccd3ee5c0f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swap_horiz Switch SetupSimpleDialog('orgContextList', 'Organizations', 'contextSwitch--navheader', '/Main/Everest/OrganizationContext/Index.mr', '', 'autoOpen:false,width:800,height:480,modal:true,draggable:false,resizable:false'); </value>
      <webElementGuid>b5d1875c-2dd0-4667-a3a2-c8d2999aea58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contextSwitch--navheader&quot;)</value>
      <webElementGuid>327aee30-fbc1-4aa9-aec6-f0f2b280fab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='contextSwitch--navheader']</value>
      <webElementGuid>8c8bcb4c-0ef0-4800-b7d5-d13478ad67bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='exit_to_app'])[1]/following::a[1]</value>
      <webElementGuid>e4ee3f78-a61f-4a6e-8dfc-17c2049c8443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Switch']/parent::*</value>
      <webElementGuid>07a6ea3b-7f3b-48f7-8898-bf72c1304af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>0e26dddf-ae74-4473-82af-cb40fbb2d085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>e0666157-134d-4a02-8863-26ac60a24d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'contextSwitch--navheader' and @href = 'javascript:void(0);' and (text() = concat(&quot;swap_horiz Switch SetupSimpleDialog(&quot; , &quot;'&quot; , &quot;orgContextList&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Organizations&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;contextSwitch--navheader&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;/Main/Everest/OrganizationContext/Index.mr&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;autoOpen:false,width:800,height:480,modal:true,draggable:false,resizable:false&quot; , &quot;'&quot; , &quot;); &quot;) or . = concat(&quot;swap_horiz Switch SetupSimpleDialog(&quot; , &quot;'&quot; , &quot;orgContextList&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;Organizations&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;contextSwitch--navheader&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;/Main/Everest/OrganizationContext/Index.mr&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;autoOpen:false,width:800,height:480,modal:true,draggable:false,resizable:false&quot; , &quot;'&quot; , &quot;); &quot;))]</value>
      <webElementGuid>b1ddd141-043f-421b-8f40-26c6ca499c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
