<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SIL</name>
   <tag></tag>
   <elementGuidId>6381b294-985f-4b9c-ac92-c651bab86ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fw-multiselect-dropdown[@id='departmentSelect']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-select.u-no-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SIL&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17d9e3c3-7e3e-403f-8ad9-512c157b4e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-select u-no-wrap</value>
      <webElementGuid>9d19378a-2102-4c33-b4e2-f4645e503c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIL</value>
      <webElementGuid>ca837c59-7f91-4aab-92c4-26dd5837160c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departmentSelect&quot;)/div[@class=&quot;input-select u-no-wrap&quot;]</value>
      <webElementGuid>20c5b1d4-f313-4620-b607-203029f9286b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fw-multiselect-dropdown[@id='departmentSelect']/div</value>
      <webElementGuid>c0f0cfdd-4a04-4d7a-80df-e46c49ed4889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[1]/following::div[1]</value>
      <webElementGuid>c2f97c4b-cdb7-4d3b-b7b3-cff5e70e4702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Off Review'])[1]/following::div[3]</value>
      <webElementGuid>0a4a9d86-7523-4850-ba50-71c44cc00880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::div[1]</value>
      <webElementGuid>53285aa1-e41c-4e6e-bdb6-63604d555730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submitted Date'])[1]/preceding::div[1]</value>
      <webElementGuid>fb2175cc-67a8-40b9-9e47-1d04dd4b8ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIL']/parent::*</value>
      <webElementGuid>9f84a27c-91ad-4086-a9c7-ae8c93b33cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fw-multiselect-dropdown/div</value>
      <webElementGuid>b63bc287-2b55-4f94-a498-c8981553f195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SIL' or . = 'SIL')]</value>
      <webElementGuid>b0c03609-8dc2-4765-97b3-adfd57bd5f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
