<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Return to Process Payroll  Review Payroll_7ceae1</name>
   <tag></tag>
   <elementGuidId>66fe7633-7b3f-4276-ac42-0b5a62eb3ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.back-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'&lt;&lt; Return to Process Payroll / Review Payroll History')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&lt;&lt; Return to Process Payroll / Review Payroll History&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26f50ac3-0a99-4538-aae5-2910c708ee4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-link</value>
      <webElementGuid>30694ad9-5c44-4ea8-be94-01883c9bfc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edge5/everest/InputSheet/Back.mr</value>
      <webElementGuid>5c861c98-003b-45f0-b245-32cfadd6ccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;&lt; Return to Process Payroll / Review Payroll History</value>
      <webElementGuid>fa7b67cf-0586-4a4e-8a41-a551f5f03072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;material-icons--loaded&quot;]/body[@class=&quot;body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;work-surface&quot;]/div[@class=&quot;work-surface__content&quot;]/div[@class=&quot;work-surface__content-inner&quot;]/div[@class=&quot;content&quot;]/a[@class=&quot;back-link&quot;]</value>
      <webElementGuid>30bf9225-078c-4241-a963-635b77df9488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'&lt;&lt; Return to Process Payroll / Review Payroll History')]</value>
      <webElementGuid>dd6612b2-b934-4802-85c7-4dcdacfa3ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='refresh'])[1]/following::a[1]</value>
      <webElementGuid>d7c9ef3b-4f14-4e85-9927-15f046481300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll Input'])[1]/preceding::a[1]</value>
      <webElementGuid>0887ce32-36cd-41c6-842a-3cf6b4f310ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Number: 11 - 2024'])[1]/preceding::a[1]</value>
      <webElementGuid>1ac7212b-3a43-49c0-8b1b-7c281340b4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;&lt; Return to Process Payroll / Review Payroll History']/parent::*</value>
      <webElementGuid>33942b96-9be9-4102-aed8-febd8d33fe78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edge5/everest/InputSheet/Back.mr')]</value>
      <webElementGuid>cd61db55-f586-4954-8f24-07fe7a415f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>2c2ac06d-ed65-4c3f-90b1-fb4d44781fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edge5/everest/InputSheet/Back.mr' and (text() = '&lt;&lt; Return to Process Payroll / Review Payroll History' or . = '&lt;&lt; Return to Process Payroll / Review Payroll History')]</value>
      <webElementGuid>ee399767-e971-4ac0-8cf9-5e69565395f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
