<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_navigate_before_date-toolbar__input i_9a347a</name>
   <tag></tag>
   <elementGuidId>fdb2424d-309c-4c7e-bb56-dea3a8058821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.date-toolbar__input.input-text.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Find pay schedule by date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57951e66-8a4b-4fcb-9dec-0c83e897677b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>110eb37f-0f85-472e-8869-422bf4120292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Find pay schedule by date</value>
      <webElementGuid>9e6d084a-e4c6-434e-b281-128146f23609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-toolbar__input input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b00a490a-7316-4aff-a975-f88d3338916d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;material-icons--loaded&quot;]/spa-app[1]/fw-framework-body[1]/fw-content[1]/main[1]/spa-my-schedule-page[@class=&quot;routed-container ng-star-inserted&quot;]/spa-my-schedule[@class=&quot;ng-tns-c532717066-5 ng-star-inserted&quot;]/div[@class=&quot;work-surface u-height--100 ng-tns-c532717066-5&quot;]/div[@class=&quot;work-surface__content ng-tns-c532717066-5 ng-trigger ng-trigger-fadeIn ng-star-inserted&quot;]/div[@class=&quot;header-block ng-tns-c532717066-5&quot;]/spa-schedule-navigator[@class=&quot;navigator ng-tns-c532717066-5&quot;]/div[@class=&quot;date-toolbar&quot;]/div[@class=&quot;u-flex date-toolbar__label-wrapper&quot;]/div[@class=&quot;date-toolbar__label-content&quot;]/input[@class=&quot;date-toolbar__input input-text ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>8768cea0-2ddb-4635-8080-6e3a74326ae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>026a885e-ee7f-4ed6-9a83-128611e9294c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0813a12f-00b7-4f37-8ae9-3b22d1d3de31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>79e1ced4-8507-4fb1-9d02-186506431675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
