<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Schedule_startDate</name>
   <tag></tag>
   <elementGuidId>26c5c31b-451a-41ff-b989-6e5b1970aba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#startDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b2da733-05ad-4de5-9d2e-13f41533dde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6778a555-b664-49f7-b18a-cc5d760a2bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>179dc6e9-2b6b-46fa-8918-e4efe701c77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>fe7b4e44-c0c6-4824-951c-47f2fe2ce482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cfb42021-adba-4a10-a699-90ddf0beace8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>78ebba26-4fa7-4c61-ae2b-84c91d40cc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDate&quot;)</value>
      <webElementGuid>62a9d10e-9a0d-4084-a352-697fdf86b5f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDate']</value>
      <webElementGuid>41ed24ac-6db4-4cf1-a683-746e54ee5d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>43106fef-54c8-4e2e-b383-98e08751534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startDate']</value>
      <webElementGuid>38818715-d718-43a9-88f9-6ae26b2ff1e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
