<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Daily</name>
   <tag></tag>
   <elementGuidId>c964aedf-2a0f-44a9-88e8-88c66b90bff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frequency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fw-select[@id='frequency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Daily&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>7800d143-9a04-4a16-b2b3-198e33c0ff77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frequency</value>
      <webElementGuid>941be0c6-c96b-4beb-96ed-761a54fb5176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Frequency</value>
      <webElementGuid>5b588b64-8fa9-46d1-8dfb-fb0317416a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>Id</value>
      <webElementGuid>ee618357-68f3-4c8c-bce6-b7eed015ac86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>1721ac3b-56de-4e3d-800d-5ce4de41fd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Frequency</value>
      <webElementGuid>5e6a02fa-8a12-4872-ba40-e349dc9ae31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select frequency-select ng-valid ng-touched ng-dirty</value>
      <webElementGuid>4d97ea97-2a6f-4fd9-aad5-f2c07cd8c18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b994342-c35d-40f8-8eba-23c1d627d194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Daily</value>
      <webElementGuid>2bb0e931-bff0-4886-85ef-368cb730e7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daily</value>
      <webElementGuid>e82c0035-eec4-46f0-9ede-15347440836f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frequency&quot;)</value>
      <webElementGuid>8cff5743-6200-4e5c-a21d-dc502d76ddb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//fw-select[@id='frequency']</value>
      <webElementGuid>1906fb26-2001-4681-b3a5-3db680bd8176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recurrence'])[2]/following::fw-select[1]</value>
      <webElementGuid>a1efc6e7-c3e7-450f-9359-bd912d35c6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No pay codes allocated to this shift.'])[1]/following::fw-select[1]</value>
      <webElementGuid>3033cbba-1941-4495-ab05-1f2a5fe92812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun, 10-Mar-2024'])[2]/preceding::fw-select[1]</value>
      <webElementGuid>33722b95-0ba3-41d5-8ba1-df5efe2fedc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/fw-select</value>
      <webElementGuid>573fd01f-5844-42cc-b522-81dde6a2b3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'frequency' and @title = 'Daily' and (text() = 'Daily' or . = 'Daily')]</value>
      <webElementGuid>5d744055-2436-4cf1-ab8d-24d893b9bf09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
