<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Does not Repeat</name>
   <tag></tag>
   <elementGuidId>59bcd2fd-6f27-4a50-9c6a-b95eb832af16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frequency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fw-select[@id='frequency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Does not Repeat&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>d4a7e199-9b9c-4fed-97be-397401380c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frequency</value>
      <webElementGuid>e406945d-9873-4e23-8123-0ca17e92902f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Frequency</value>
      <webElementGuid>e92837d6-8bee-4754-bc8b-d6d2d84854bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>Id</value>
      <webElementGuid>2e8dc3e0-e814-47a8-91e3-a80dc162a814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>0e06c9f2-829f-43a9-82ea-c999d35c9cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Frequency</value>
      <webElementGuid>2f164845-109e-4098-8530-4a7565a3be35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select frequency-select ng-valid ng-touched ng-dirty</value>
      <webElementGuid>9323697f-9942-4ef7-bf81-6078bb407dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8a4bc406-f682-4cb8-b7a2-452b3ef5c6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Does not Repeat</value>
      <webElementGuid>289052ce-458c-412f-95ff-8abbe395f691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Does not Repeat</value>
      <webElementGuid>2b9d12d6-3586-4bda-a102-8606fabde4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frequency&quot;)</value>
      <webElementGuid>7cd16aec-4cea-4dcd-bbae-e5cb421c7cdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//fw-select[@id='frequency']</value>
      <webElementGuid>a1450067-80b8-4443-b4c7-c094ef88be00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recurrence'])[2]/following::fw-select[1]</value>
      <webElementGuid>cfe4d3f7-01ae-4074-8589-da1c2322b3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No pay codes allocated to this shift.'])[1]/following::fw-select[1]</value>
      <webElementGuid>4dd7db06-0251-47e4-abd7-79bf66eeeefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon, 6-Oct-2025'])[2]/preceding::fw-select[1]</value>
      <webElementGuid>9d1e1b77-2604-4303-9701-d017dd40b57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/fw-select</value>
      <webElementGuid>e65ead48-ec3b-4e86-8bc2-5aacdc54615b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'frequency' and @title = 'Does not Repeat' and (text() = 'Does not Repeat' or . = 'Does not Repeat')]</value>
      <webElementGuid>ef59c454-12e7-4c40-b164-e91ff38d2b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun, 10-Mar-2024'])[2]/preceding::fw-select[1]</value>
      <webElementGuid>544a6a7a-68b3-49c5-92b9-306a11489393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
