<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End After_occurrences</name>
   <tag></tag>
   <elementGuidId>fa5c06d0-ed7c-471d-9570-260630802def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#occurrences</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='occurrences']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;occurrences&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>849f5a53-13e9-4976-96b6-5973db14a136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>de7b3897-5059-4f67-b7bc-2fc97631838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7154f9c0-9896-40b7-9e90-65fd4c38c26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occurrences</value>
      <webElementGuid>4df6f57b-0ea2-415d-aee7-d852226afcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Occurrences</value>
      <webElementGuid>0a95a2a7-3e01-45fa-9692-9c9b874adce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text u-m-left--half occurrences ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>e02c133e-b181-418e-b5ac-f1c173946d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occurrences&quot;)</value>
      <webElementGuid>a6883bd8-d798-4ab3-bfdf-18f95e396502</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='occurrences']</value>
      <webElementGuid>97447343-03a1-4f48-b940-99e04e9fe6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-workblock-recurrence-range/div/div[2]/div[2]/div/input</value>
      <webElementGuid>1e9b05d2-9273-4fca-b94c-75f603f54d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'occurrences']</value>
      <webElementGuid>c914df9a-4e5c-43eb-8562-97152fe1800d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
