<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_day(s)_everyWeekday</name>
   <tag></tag>
   <elementGuidId>ecc79137-7608-4b69-b8d7-2f318c43e8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#everyWeekday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='everyWeekday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Every Weekday&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20ea3a99-ec77-4266-99df-1fbf46cad9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6ed78f10-90e7-40ac-af1c-5f17e5e85f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>everyWeekday</value>
      <webElementGuid>4023f17e-b7d9-43ec-a8d9-85f6de831d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>EveryWeekday</value>
      <webElementGuid>1a3432c3-c343-4bc3-8fde-b31956c36e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DailyOption</value>
      <webElementGuid>00a701b4-21c9-4b02-9d1d-bd094a9c4a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2b1d19f5-2b7f-4f57-a437-007dd5c8d2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;everyWeekday&quot;)</value>
      <webElementGuid>6d21f251-c5ba-4ff8-9524-5455edaa7625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='everyWeekday']</value>
      <webElementGuid>f13f7321-6a94-4f38-96a0-906382466f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-workblock-recurrence-daily/div/div[2]/input</value>
      <webElementGuid>05b28314-cee4-4245-af41-1b89ed97fb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'everyWeekday']</value>
      <webElementGuid>e4fede5c-28a3-48b7-b3c9-89ca9c4f92c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
