<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_occurrences_endBy</name>
   <tag></tag>
   <elementGuidId>9bcd3851-aba5-4ce8-b83d-a50a47dea964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;End By&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebeeb13e-0d28-49cb-a063-9ec2605ede5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>97dd23f5-7086-44eb-b711-5d4e8fd76d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endBy</value>
      <webElementGuid>4be67694-372c-45f7-848c-3b8b30ce9b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>EndAfterDate</value>
      <webElementGuid>923b0563-26f2-4797-a7ef-40e3d3c24d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>EndDateOption</value>
      <webElementGuid>1d358861-5d5b-4325-8ca4-d942405520da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>da83005b-90c4-439b-a967-affe7c3e9073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endBy&quot;)</value>
      <webElementGuid>4baca791-9be8-4929-bce6-972c9087a852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endBy']</value>
      <webElementGuid>57875080-78c0-4fd6-8c0c-b10a9760cc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-workblock-recurrence-range/div/div[2]/div[3]/input</value>
      <webElementGuid>980be7fb-46c2-471d-946a-06e984848b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'endBy']</value>
      <webElementGuid>0c1fbedf-f875-40df-bbb6-1aa9ea26678e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
