<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End By_endByDate</name>
   <tag></tag>
   <elementGuidId>973af2af-86c4-4fb2-8c63-c6b9e00cb8a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endByDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endByDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#endByDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a64aa5f-4396-4d46-95f4-548b8f51a771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79aa9a54-fa04-462d-8e1d-e4698ed71826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endByDate</value>
      <webElementGuid>e7d0c815-7c59-451e-89dd-32e92dbb8b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>EndByDate</value>
      <webElementGuid>563a3285-9475-45d8-8538-a1cfe6ad7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text end-by-date ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b72821da-a9b1-43b6-b1bc-0aa338c307ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6b83f18c-dfc4-4a14-b128-7893f827046c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endByDate&quot;)</value>
      <webElementGuid>7148a8b2-3408-4e4e-8872-0f06d4ee66a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endByDate']</value>
      <webElementGuid>9661f30a-1df7-42cb-aea2-e6843b7e7410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>6155f8c8-cdf5-4d3d-b278-8f6c7eceffa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'endByDate']</value>
      <webElementGuid>6bc708fc-1eb3-44c3-ad8a-a09282f6678d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
