<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No end date_endAfter</name>
   <tag></tag>
   <elementGuidId>98e3b2ec-dba4-483e-a0d8-275f093cfd27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endAfter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endAfter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;End After&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>023ecc1b-0d85-43ad-920a-f9b10e125059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>19db49ab-be08-449d-81ef-efe6ffea2cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endAfter</value>
      <webElementGuid>b145ea78-1239-407a-b3fc-a3709b2be7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>EndAfterOccurences</value>
      <webElementGuid>54b85eb5-4644-4a3f-9cf9-2368e4687933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>EndDateOption</value>
      <webElementGuid>6dcef1e3-cc66-4b46-b67d-c23cd567972f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>075eed60-0e93-437e-883c-eff80ac18c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endAfter&quot;)</value>
      <webElementGuid>10accf6c-e1a8-4008-a7b9-b24f0d29b7a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endAfter']</value>
      <webElementGuid>e61de7c9-f61d-4a13-9ee4-4164b20d0ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-workblock-recurrence-range/div/div[2]/div[2]/input</value>
      <webElementGuid>c81b59db-b8f1-4df2-863f-17fbd135adc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'endAfter']</value>
      <webElementGuid>a101690e-9aa0-4a97-a5fb-088b52bf3ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
