<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_startDate</name>
   <tag></tag>
   <elementGuidId>52daad41-ebc5-42f4-a4fb-7e6c920247c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'startDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-row-item.date > #startDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='startDate'])[2]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#detailsTab #startDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>805150cd-4628-4cec-a89f-78405f0f64d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a87031a7-b019-42b5-9323-d9592390580c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>63b46f5d-d589-4c8c-86c5-573e3a18d9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>0c8a8953-904a-4714-a92c-4a7193bb6999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3a291e9e-a9f9-4232-8b08-2f76f74534b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0f42262a-813a-4430-af1e-926a13fe1e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailsTab&quot;)/div[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/fieldset[1]/div[@class=&quot;u-flex form-row&quot;]/div[@class=&quot;form-row-item date&quot;]/input[@id=&quot;startDate&quot;]</value>
      <webElementGuid>95ea1fad-ba2b-4bea-b394-df806529c1bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='startDate'])[2]</value>
      <webElementGuid>565b889c-5f63-493f-a386-d656edee21e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailsTab']/div/form/fieldset/div/div/input</value>
      <webElementGuid>87fdd97e-2b45-48a7-9143-0b0a6266ec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/div/div/input</value>
      <webElementGuid>8c0d7b6c-c038-41f7-a98d-9f7b129dea2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startDate']</value>
      <webElementGuid>83f691f0-416d-4d8f-8e2d-9cedf139b18a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
