<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_occurrences_endBy</name>
   <tag></tag>
   <elementGuidId>9bcd3851-aba5-4ce8-b83d-a50a47dea964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;End By&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbe1b61f-bbbc-490b-ba05-1fb84b155685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3fca9b95-1db7-44f2-b6f5-848b45cf7e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endBy</value>
      <webElementGuid>fc443b3f-5b4e-4e41-b657-c366b51791a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>EndAfterDate</value>
      <webElementGuid>ae0b2664-ae0a-417c-8cdd-1125f5796811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>EndDateOption</value>
      <webElementGuid>aaa38979-1d33-4fc4-8600-bd12815e7b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9f6c5ed1-ea0d-4809-a2f9-9c4b1f644297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endBy&quot;)</value>
      <webElementGuid>fc7ad0cb-2820-4045-94af-15f5fe136736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endBy']</value>
      <webElementGuid>39d3f2b2-cb43-4152-a5d5-1bf28f4c9e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//spa-workblock-recurrence-range/div/div[2]/div[3]/input</value>
      <webElementGuid>3913a4c0-fa78-47e5-b85e-c139602ac3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'endBy']</value>
      <webElementGuid>53f26caf-523d-4983-8d41-706a38e45c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
