<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_endDate</name>
   <tag></tag>
   <elementGuidId>98f5dd49-c88d-4009-932b-3891528bb280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-row-item.date > #endDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='endDate'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#detailsTab #endDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f3dc54e-0b6d-4c9c-b1dd-456cbc2bc24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47d63659-ceb0-4030-b944-ced95a63c3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>e9646b95-af2a-4742-8b33-15fa942c25a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>End</value>
      <webElementGuid>6afed092-0070-45b2-bd36-302162045094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text date-picker ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b7aff466-74cf-47ba-8931-5fb5a1be6899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>64cd793f-d610-47b3-9b2d-90206196ac17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailsTab&quot;)/div[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/fieldset[1]/div[@class=&quot;u-flex form-row&quot;]/div[@class=&quot;form-row-item date&quot;]/input[@id=&quot;endDate&quot;]</value>
      <webElementGuid>0f5ab8b9-73df-429e-8beb-f84edfb2feb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='endDate'])[2]</value>
      <webElementGuid>c6a5f8ed-12f3-483b-b4f7-4cf5e2baa682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailsTab']/div/form/fieldset/div/div[3]/input</value>
      <webElementGuid>6cb70cb2-2067-4fd8-8999-ab9ac3355432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[3]/input</value>
      <webElementGuid>4550d634-71cf-4c39-9996-203879870784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'endDate']</value>
      <webElementGuid>cdc9b779-f323-4b39-8267-e6224792cd8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
