<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_startDate</name>
   <tag></tag>
   <elementGuidId>52daad41-ebc5-42f4-a4fb-7e6c920247c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-row-item.date > #startDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='startDate'])[2]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#detailsTab #startDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d45fbe1-a3fd-4984-9699-625249950599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b43b682e-ef97-4f64-bf91-b2c813702aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>d21fc3aa-c89f-48bc-8a1b-f9e3961e3817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>9a1557b2-920d-427e-b05c-c73f137b235c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>de34f5ab-8d64-40a2-8dff-c433bdec19b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3c8078e-bb4a-41af-9912-1ad0c1d3c19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailsTab&quot;)/div[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/fieldset[1]/div[@class=&quot;u-flex form-row&quot;]/div[@class=&quot;form-row-item date&quot;]/input[@id=&quot;startDate&quot;]</value>
      <webElementGuid>7b87b6ac-ea15-45d6-9ace-623d5fc63a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='startDate'])[2]</value>
      <webElementGuid>e070640c-1a5c-481c-9284-3e294a07cc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailsTab']/div/form/fieldset/div/div/input</value>
      <webElementGuid>129902ab-1a3f-4e00-abf0-05a610ef98b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/div/div/input</value>
      <webElementGuid>465160e5-c5c3-4fe0-81a8-83ef28ca1e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startDate']</value>
      <webElementGuid>1837b1ad-0f24-4147-9e76-0840e1ea6fd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
