<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Home Department filter_list</name>
   <tag></tag>
   <elementGuidId>33b3d866-6ffe-4f0e-9fe1-7e045c2cca95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='filter_list'])[3]/following::th[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.col--home-department</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=columnheader[name=&quot;Home Department filter_list&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>74869af1-907c-434c-8383-024554cfae9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>c0d8adaf-22a4-412e-82ba-069fec89b45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fwsortby</name>
      <type>Main</type>
      <value>HomeDepartmentName</value>
      <webElementGuid>579ce60c-dcae-4dac-807b-62b2bd50fa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fwfilterid</name>
      <type>Main</type>
      <value>HomeDepartmentName</value>
      <webElementGuid>12af350b-f444-4262-8283-f5d1fbf0e407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fwfilterpropertyname</name>
      <type>Main</type>
      <value>HomeDepartmentName</value>
      <webElementGuid>c7e13341-dbbd-4abe-9f1a-e32bf1e3a752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col--home-department</value>
      <webElementGuid>ba69890f-e5e1-4da7-8cc3-252086ed2897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Home Department filter_list</value>
      <webElementGuid>828c7bcd-3a80-48bf-acf2-c2a08d248f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;material-icons--loaded&quot;]/spa-app[1]/fw-framework-body[1]/fw-content[1]/main[1]/spa-time-off-admin-container[@class=&quot;routed-container ng-star-inserted&quot;]/spa-time-off-admin[@class=&quot;work-surface__content ng-star-inserted&quot;]/spa-request-admin-table[1]/table[@class=&quot;grid-lite&quot;]/thead[1]/tr[1]/th[@class=&quot;col--home-department&quot;]</value>
      <webElementGuid>53a99aab-48f8-4a19-8274-3a0c132017d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='filter_list'])[3]/following::th[1]</value>
      <webElementGuid>00209784-51ce-4cca-9302-74b221499ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home Department']/parent::*</value>
      <webElementGuid>2e5e0695-0ac3-41ef-b2b7-e5441e4fed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]</value>
      <webElementGuid>cd3ecc07-b049-4bbe-a4f9-0d5d83c45798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = ' Home Department filter_list' or . = ' Home Department filter_list')]</value>
      <webElementGuid>78e48a38-b80c-43d1-aa2c-f365b628ba4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
