<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Department Field 1_field01Value</name>
   <tag></tag>
   <elementGuidId>2ff21c47-aa7c-4ea3-a8b8-f3e8042cb095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_field01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_field01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txt_field01</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b38b94d-bdca-41f0-b7b9-af9575ed6a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa46752d-32d0-410b-a003-d059c63eb930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_field01</value>
      <webElementGuid>3e5ec8dd-a34d-4198-9362-34fa5985bad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field01Value</value>
      <webElementGuid>a28b8bfe-131c-4ff3-ab33-03be505e0d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5168c512-23cb-4547-a738-8c2a17512a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_field01&quot;)</value>
      <webElementGuid>08775f14-df95-4a72-89a5-fe9ab351debe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_field01']</value>
      <webElementGuid>4db67056-599b-4298-bfaf-8fdec18b1738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9365901a-1b42-427c-a6a3-cfc8bbacf278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_field01' and @name = 'field01Value']</value>
      <webElementGuid>fa09a64c-ed4b-4664-9cb0-9b6fb170a577</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
