<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fw-select_Input value type</name>
   <tag></tag>
   <elementGuidId>87dd6b70-d668-4aa0-9be7-baade7b04780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputTypeObjId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'inputTypeObjId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Hours&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fw-select</value>
      <webElementGuid>c58c832c-f02b-47c8-974d-92a41c1b087c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputTypeObjId</value>
      <webElementGuid>f014869a-d0bb-437b-b75e-58d163756706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>3d405815-7fa2-438d-b0a0-230371957796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valuefield</name>
      <type>Main</type>
      <value>ObjId</value>
      <webElementGuid>d20f5ded-b61a-4556-b9fb-d1ad5dbcf0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>InputTypeObjId</value>
      <webElementGuid>7f9c94c7-0562-4955-a4db-95360d7f2d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignwith</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>bc9852b6-c942-464d-9c6b-fbd8302d3c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-select input-select ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7515a7cc-0819-463e-829a-56553ee89f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>584ddbc1-6fa9-4ae6-9cf2-d01e4dc99bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>30bf8d68-a5a1-43a2-b285-0582eca782b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Input value type</value>
      <webElementGuid>76b82422-09f6-4b58-b9fb-856ad9703471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>b604df52-cee4-43d1-975e-52f81514203f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fec515dfd93c0de8f5fcf167069b9c87</value>
      <webElementGuid>9e44ba37-37e2-4f95-b259-59bbc34015aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>5e6371fa-70fd-4186-8014-7b153bd66889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'inputTypeObjId']</value>
      <webElementGuid>f3f734e1-cf19-44ef-843c-dc2433081866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fw-select[@id = 'inputTypeObjId' and @title = 'Hours' and (text() = 'Input value type' or . = 'Input value type')]</value>
      <webElementGuid>f7c87bd0-71da-4f4d-8ccb-213f1fb375ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
