<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Allow</name>
   <tag></tag>
   <elementGuidId>8836b167-763a-4b7f-9f7b-1290bfff48aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isOverrideAllowed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'isOverrideAllowed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Allow:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9f43634-9f16-4900-ba43-3505fa0ae261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>783f0928-f682-41aa-a82e-ad7a722d84a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isOverrideAllowed</value>
      <webElementGuid>754dc2aa-dab1-47cd-9d7e-846c0e45967a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>IsOverrideAllowed</value>
      <webElementGuid>9840ab00-dde7-45f3-98e9-55b7d9daf17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-checkbox ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f21bb2d5-cd84-46a4-9575-4ba16d30d372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow</value>
      <webElementGuid>9605f507-66d2-4bc6-b3d1-2afcf9bb3282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-070ad9000a203c2c0deccf2912c575df</value>
      <webElementGuid>2e88a859-6724-41b3-9b5a-cef9696c140b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'isOverrideAllowed']</value>
      <webElementGuid>9aae7ccd-31c0-4925-8f81-91dfab1aee8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'isOverrideAllowed']</value>
      <webElementGuid>52aad302-f588-47c9-8b06-59660573277b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isOverrideAllowed' and (text() = 'Allow' or . = 'Allow')]</value>
      <webElementGuid>6e6fcce9-6077-4f96-bb6a-23c57067ad9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
