<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Formula Code</name>
   <tag></tag>
   <elementGuidId>28347d28-d8c1-4ccd-85f2-e5208a6e25d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formulaCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formulaCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Formula Code:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8af13fce-808a-4267-812f-88c3e480fa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>366de241-4d44-47a1-9c4a-e8c74c74e9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formulaCode</value>
      <webElementGuid>55ec4411-f560-48a7-b1c9-d22404d051e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>FormulaCode</value>
      <webElementGuid>316bd954-02fe-4184-a43b-0d325d3ff174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>75545eb2-c970-4a5c-ba41-49347e957ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formula Code</value>
      <webElementGuid>fc20fc5a-de01-4c9a-b33a-c91ef3db2aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d58b1de1ad9ef82ded1b3f1c88b97baf</value>
      <webElementGuid>d2312e6d-3ede-4b1e-a551-cd70c951766f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formulaCode']</value>
      <webElementGuid>b5d22f28-2bfc-4c42-8b43-d405a6134946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formulaCode']</value>
      <webElementGuid>90e4a310-1664-4aaa-b86f-acb335204530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formulaCode' and (text() = 'Formula Code' or . = 'Formula Code')]</value>
      <webElementGuid>312bcb12-de10-49de-9924-f814287040ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
