<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New pay rate</name>
   <tag></tag>
   <elementGuidId>ec803db0-65ad-42d8-b82c-a614ee61837f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newPayRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'newPayRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;New pay rate&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd47ded2-b1fe-4902-9938-5e78db17aaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>118f2777-d150-40fc-b38c-df4a1add15f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPayRate</value>
      <webElementGuid>592f7692-758b-4324-8ed9-c2e3bce2dcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NEWPAYRATE</value>
      <webElementGuid>14ee8206-94b6-478c-b907-78aa9942e9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>PayRateCategoryCode</value>
      <webElementGuid>3d2c4a95-fb56-4a37-b978-b20e8208ac70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ff485212-8204-41f6-8ebb-786f6ca8824a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New pay rate</value>
      <webElementGuid>f335bfee-633a-475f-8ff8-d3d569f1d8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8b37e546686c22fff7003eb853550a25</value>
      <webElementGuid>00ce3b05-047b-4890-8594-835dad3ea766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'newPayRate']</value>
      <webElementGuid>4b56c41a-eaca-43f4-9784-5ceed2892195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'newPayRate']</value>
      <webElementGuid>5021690b-5926-4d23-bcdb-66950171df92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'newPayRate' and (text() = 'New pay rate' or . = 'New pay rate')]</value>
      <webElementGuid>48a7f205-78ea-4229-863c-0661c6989cdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
