<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_policyTypeHomeDepartmentOnly</name>
   <tag></tag>
   <elementGuidId>f0ea8788-8838-410f-93cc-36dd82a75790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policyTypeHomeDepartmentOnly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'policyTypeHomeDepartmentOnly']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#policyTypeHomeDepartmentOnly</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d312f8d4-fec7-492e-b03b-995c7f782b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policyTypeHomeDepartmentOnly</value>
      <webElementGuid>fad1c698-ccc6-42c0-96aa-7966bdabf340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f48f9b0f-b91a-466f-85d6-1d34b636e47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>HOME_DEPARTMENT_ONLY</value>
      <webElementGuid>5df3763b-737b-4ca9-9a8a-bffcb1f70f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>PayrollInstructionApplicationPolicyTypeCode</value>
      <webElementGuid>05df8da8-e032-4079-866d-3486f02b07ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e63f043f-dbc7-415c-b1b3-d0bc5dc96326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>policyTypeHomeDepartmentOnly</value>
      <webElementGuid>13521a77-153f-4f34-a959-3ed4535c1600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f5162a77f1e772f896ac84a475966f8e</value>
      <webElementGuid>e448695a-1938-40e1-97e6-fd0ff897478b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'policyTypeHomeDepartmentOnly']</value>
      <webElementGuid>9d26071b-62ce-48d8-8e07-16b47608c8b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'policyTypeHomeDepartmentOnly']</value>
      <webElementGuid>f429f18e-f401-4558-878b-33ae639ee863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'policyTypeHomeDepartmentOnly' and @type = 'radio' and (text() = 'policyTypeHomeDepartmentOnly' or . = 'policyTypeHomeDepartmentOnly')]</value>
      <webElementGuid>89f13e4b-034c-47a4-8f25-954cc72df0a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
