<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_defaultFormula</name>
   <tag></tag>
   <elementGuidId>512f548d-73b1-4ffd-8c63-210475e65cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#defaultFormula</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'defaultFormula']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#defaultFormula</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>47bf3b4b-247d-4aaa-8fb2-ac0aaaded03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>49657af1-22c6-435f-9807-6c89a6064555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>f4480a1a-b6d3-4cf8-b032-c0031515a34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5301b44c-5646-4dc3-8ec7-4e7ba5a7863c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>7429138f-fa00-4be9-8211-545de5533a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4943a36-435d-4c12-98be-5cb2985d482f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>DefaultFormula</value>
      <webElementGuid>362dbc2f-7e1a-4c96-ab27-84705a870382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>81007d20-2717-4dfd-8afc-e6327a154b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>e08903af-cbf9-4b61-b3b9-b11f8793e801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>defaultFormula</value>
      <webElementGuid>5266c880-5e91-4410-a257-ba77f560ead7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-287cb90c8af5d1c88243b2405e542df6</value>
      <webElementGuid>38e4c9e9-fd84-434d-8628-03f62ebf1f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'defaultFormula']</value>
      <webElementGuid>ec58d686-b30a-4982-86af-4611559755c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'defaultFormula']</value>
      <webElementGuid>76d1fcea-4e15-4be1-8b14-8f904a3860fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'defaultFormula' and @id = 'defaultFormula' and (text() = 'defaultFormula' or . = 'defaultFormula')]</value>
      <webElementGuid>b3dde7bf-f1f9-4329-9e20-603e7cadaeab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
