<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Department Field Settings_fiel_da0194</name>
   <tag></tag>
   <elementGuidId>3c2fda73-f85d-477e-9ad4-202fbb088e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chk_field01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chk_field01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Custom Department Field #1:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c81efe1b-33e6-4b7a-9bd0-6730ce37a843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>75784ca6-9f3c-408d-836b-e2d0902601d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chk_field01</value>
      <webElementGuid>a92f291f-def3-4d17-9d62-f6a84cb0f547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field01Enabled</value>
      <webElementGuid>f41991b2-a4c6-4a29-a8fc-f7fcf5dca986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-touched</value>
      <webElementGuid>0d47fd8d-340d-4db5-9880-6868620d5ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chk_field01&quot;)</value>
      <webElementGuid>79581f3c-a40b-4860-be61-d4d5287ea1c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chk_field01']</value>
      <webElementGuid>fa39d87e-c06c-482e-9bc9-b6a5126ba358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>2ceb432e-610e-4928-9c80-308ba659d1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'chk_field01' and @name = 'field01Enabled']</value>
      <webElementGuid>7fdaf438-4c19-4488-b3a0-1362305e6371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
