<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Code_department.Code</name>
   <tag></tag>
   <elementGuidId>c0690027-4d3b-48df-80fc-a84d81c77499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#department_Code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='department_Code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#department_Code</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6d2b96b-63ea-4f3a-8664-0159eafcabc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e4fb3e0-bc84-4a93-a450-b46526c7f360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department_Code</value>
      <webElementGuid>2d946050-67f7-4068-9383-63b127182f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>department.Code</value>
      <webElementGuid>b77d893c-403f-4c4a-9920-c7c30ac92089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>95879fb3-a6fb-495f-ba51-198a78a082e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text dirty</value>
      <webElementGuid>76e8127a-42c0-4e05-a648-1e0a6ac5512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department_Code&quot;)</value>
      <webElementGuid>5bbde6e6-78ce-49f6-8c68-92f411298819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='department_Code']</value>
      <webElementGuid>b16cd39b-8fda-4c97-b9b0-53cb93048998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDepartmentDetailAdd']/div/div/div[2]/input</value>
      <webElementGuid>5cb07c75-e39b-4853-9bc5-9ac8aea4387d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>988668ef-7694-4d45-92a0-d07e2edc7469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'department_Code' and @name = 'department.Code']</value>
      <webElementGuid>fcfacb8c-c37f-48d1-8923-bbd9b0d98f38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
