<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Department Name_department.Name</name>
   <tag></tag>
   <elementGuidId>c8a556f8-343c-4762-a855-425d493b38d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#department_Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='department_Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#department_Name</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf268bb1-9fd1-49a1-923c-bbaaa88e35c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d03be6ee-0726-4c1a-a55c-562cf0bbb269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>department_Name</value>
      <webElementGuid>77496fca-dbce-40f2-9438-b1b0bead696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>department.Name</value>
      <webElementGuid>d4c8824f-536f-42cf-9441-93bec1ad63cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c7851bbf-f6fa-452c-81d2-3706b7bef724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text dirty</value>
      <webElementGuid>924732ed-4c72-440e-92da-fff99717d166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;department_Name&quot;)</value>
      <webElementGuid>34d5bd98-0331-44d9-a980-0b4b0d78994e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='department_Name']</value>
      <webElementGuid>bd7dc14e-e531-479c-a84b-3217257b4475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmDepartmentDetailAdd']/div[2]/div[2]/div/input</value>
      <webElementGuid>668e2944-a994-489d-9aaf-e9105002ae8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b206a7a5-b1d0-4b04-9971-b60b1768aa80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'department_Name' and @name = 'department.Name']</value>
      <webElementGuid>0c080f82-c89b-491c-aca5-070aa14b2f5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
