<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_navigate_before_date-toolbar__input i_9a347a</name>
   <tag></tag>
   <elementGuidId>fdb2424d-309c-4c7e-bb56-dea3a8058821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.date-toolbar__input.input-text.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Find pay schedule by date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e478aac-191b-4356-8d7f-c2dc501d34b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42c6a6e5-1292-4521-966d-e48d9ba81aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Find pay schedule by date</value>
      <webElementGuid>07deaa50-b626-4349-a3c8-3de010e417cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-toolbar__input input-text ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>58718890-bf34-4bfd-90bb-0cfb873a7189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;material-icons--loaded&quot;]/spa-app[1]/fw-framework-body[1]/fw-content[1]/main[1]/spa-my-schedule-page[@class=&quot;routed-container ng-star-inserted&quot;]/spa-my-schedule[@class=&quot;ng-tns-c532717066-5 ng-star-inserted&quot;]/div[@class=&quot;work-surface u-height--100 ng-tns-c532717066-5&quot;]/div[@class=&quot;work-surface__content ng-tns-c532717066-5 ng-trigger ng-trigger-fadeIn ng-star-inserted&quot;]/div[@class=&quot;header-block ng-tns-c532717066-5&quot;]/spa-schedule-navigator[@class=&quot;navigator ng-tns-c532717066-5&quot;]/div[@class=&quot;date-toolbar&quot;]/div[@class=&quot;u-flex date-toolbar__label-wrapper&quot;]/div[@class=&quot;date-toolbar__label-content&quot;]/input[@class=&quot;date-toolbar__input input-text ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>f1fcec51-9f78-472f-b601-8592dbc49f02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>593b803e-fbfb-49e6-b7bd-4992aee8e154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c59f7a8f-42c2-4ee4-9116-ab6218d29260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>dcab6ae6-a57f-4c0f-aead-45a338d98f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
