<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_notApplicable</name>
   <tag></tag>
   <elementGuidId>409e7a0f-261e-468d-a189-55d2bd9eec38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notApplicable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'notApplicable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Not applicable&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce311f49-f1d4-44ea-b75f-32d9247c8237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2da59e29-5874-4923-91cb-d045a3e6f1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notApplicable</value>
      <webElementGuid>2129c31c-82d2-48cc-9d08-2fc598aad4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>PayRateCategoryCode</value>
      <webElementGuid>bd37a6fc-fccd-4847-b1a6-eb657260cf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>73276ec8-3e51-4e82-8ded-ebbbbf2c2ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>notApplicable</value>
      <webElementGuid>a7aba0b6-557b-4409-ae70-17379e876152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4049676b09313c6fef5e56e62b3498a8</value>
      <webElementGuid>cf9de157-1082-42b1-9c6e-25a382791af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'notApplicable']</value>
      <webElementGuid>718c96c9-6a8a-4256-bb34-1c3c11b8d6c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'notApplicable']</value>
      <webElementGuid>bfe2324d-76d6-48b3-a3bb-7338bf66d5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'notApplicable' and (text() = 'notApplicable' or . = 'notApplicable')]</value>
      <webElementGuid>86e30df4-201e-4541-9eb3-2df5b6df2f9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
