<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Client 100</name>
   <tag></tag>
   <elementGuidId>26ab8303-f62c-4eaa-81af-2aaec4ee7bdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerOrganizationName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headerOrganizationName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Client 100&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e40d0e2f-f653-47c2-a173-9a34874fe05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-menu__organization</value>
      <webElementGuid>19ed1355-d7cf-43ce-9906-0f6b294327c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headerOrganizationName</value>
      <webElementGuid>295df032-94f7-4ab1-a49e-a15b35aad480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Client 100
                                        </value>
      <webElementGuid>babc742d-26f3-401c-85b5-dcb904e12613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerOrganizationName&quot;)</value>
      <webElementGuid>47a3f988-66d6-4f2e-b3d4-7f21202d81c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headerOrganizationName']</value>
      <webElementGuid>45a2315e-8c18-459d-85e5-cf8191abeb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-user-menu']/div/div/div[2]</value>
      <webElementGuid>c3552fc8-c575-4bd3-a3c0-d3cb38e939d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Darryl Stewart'])[1]/following::div[1]</value>
      <webElementGuid>9c4e76d7-e5fa-4f26-9dfa-8ea3d744cbf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='close'])[1]/following::div[7]</value>
      <webElementGuid>d7ebfdda-c979-497c-874f-a341c11fc2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='expand_more'])[1]/preceding::div[1]</value>
      <webElementGuid>e5430b15-c79c-4b87-854c-c5a84abaee18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Client 100']/parent::*</value>
      <webElementGuid>42daae92-f264-48a3-9d1a-0a312ae69381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>7f0ce00b-a6fc-40d1-bef2-357de3a48523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headerOrganizationName' and (text() = '
                                            Client 100
                                        ' or . = '
                                            Client 100
                                        ')]</value>
      <webElementGuid>18f21a7e-91a0-40a9-83c4-b1edabc4f020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
